api:
  dashboard: true
  #insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      # redirections:
      #   entryPoint:
      #     to: websecure

  websecure:
    address: ":443"
    http:
      middlewares:
        - secureHeaders@file

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true