language: python
python:
  - "3.7.4"
install:
  - pip3 install homeassistant
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get update && sudo apt-get install -y libudev-dev python-dev pkg-config
  # Cause the stream component causes travis fail?
  - sed -i -e 's/- camera/#- camera/' -e 's/^camera/#camera/' configuration.yaml
script:
  - hass -c . --script check_config -i -f
