services:
  - docker
script:
  - mv travis_secrets.yaml secrets.yaml
  - sed -i -e 's/- camera/#- camera/' -e 's/^camera/#camera/' configuration.yaml
  - echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
  - docker pull homeassistant/home-assistant:stable
  - docker run -it --rm -v $TRAVIS_BUILD_DIR:/config homeassistant/home-assistant:stable python -m homeassistant --config /config --script check_config
