language: python
python:
  - "3.6.4"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - rm -f ./packages/stream.yaml
  - mv .travis_secrets.yaml secrets.yaml
  - sudo apt install libudev-dev
