language: python
python:
  - "3.6.8"
install:
  - pip3 install homeassistant
before_install:
  - ls
  - pwd
  - mv .travis_secrets.yaml secrets.yaml
script:
  #- exit 0
  - hass -c . --script check_config -i -f
