language: python
python:
  - "3.6.4"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config -i
before_install:
  - ls
  - pwd
  - mv .travis_secrets.yaml secrets.yaml
  - sed -i -e 's/- platform: bus_times//' ~/home-assistant-config/sensors.yaml
  - sudo apt-get update
  - sudo apt install libudev-dev
