language: python
python:
  - "3.7.4"
install:
  - pip3 install homeassistant
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get update && sudo apt-get install -y libudev-dev 
script:
  - hass -c . --script check_config -i -f
