services:
  - docker
before_install:
  - docker pull homeassistant/home-assistant:stable
  - mv travis_secrets.yaml secrets.yaml
  - sed -i -e 's/- camera/#- camera/' -e 's/^camera/#camera/' configuration.yaml
script:
  - docker run -it --rm --entrypoint=/bin/bash -v $TRAVIS_BUILD_DIR:/config homeassistant/home-assistant:stable hass --config /config --script check_config
