# Doors moved to ESPHome

- platform: digital_ocean
  droplets:
    - !secret DO_host

- platform: ping
  name: Thermostat Online
  host: 10.0.0.29
  count: 2

#- platform: ping
#  name: internet_reachability
#  host: 1.1.1.1
#  count: 3
#  scan_interval: 30

- platform: mqtt
  name: "Andrew MacBook Active"
  state_topic: "sensor/andrew_macbook"
  value_template: "{{ value_json.active }}"
  payload_on: true
  payload_off: false

- platform: template
  sensors:
    # On if both backups < 10 minutes ago
    backups_complete:
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states('sensor.last_vps_backup_completed'))) < 600 and (as_timestamp(now()) - as_timestamp(states('sensor.last_nuc_backup_completed'))) < 600 }}"
    washing_machine_water_detector:
      device_class: moisture
      value_template: "{{ states('sensor.washing_machine_water_detector_alarm_level') == '0' }}"
    water_heater_water_detector:
      device_class: moisture
      value_template: "{{ states('sensor.water_heater_water_detector_alarm_level') == '0' }}"
    master_closet_motion_detection:
      device_class: motion
      value_template: "{{ states('sensor.master_closet_motion_alarm_level') == '255' }}"
