# Doors moved to ESPHome

- platform: digital_ocean
  droplets:
    - !secret DO_host

#- platform: ping
#  name: internet_reachability
#  host: 1.1.1.1
#  count: 3
#  scan_interval: 30

- platform: iss
  show_on_map: true

- platform: template
  sensors:
    backups_complete:
      value_template: >-
        {{ (as_timestamp(now()) - as_timestamp(states.sensor.last_vps_backup_completed.state)) > 200 and ((as_timestamp(now()) - as_timestamp(states.sensor.last_nuc_backup_completed.state)) > 200) }}
