# Doors moved to ESPHome

# - platform: digital_ocean
#   droplets:
#     - !secret DO_host

- platform: workday
  country: US
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]
  # add_holidays:
  #   - "2020-02-24"
  #   - "2020-04-25"

- platform: ping
  name: Thermostat Online
  host: 10.0.0.29
  count: 2

- platform: ping
  name: Andrew Work Laptop
  host: 10.0.1.27
  count: 2

- platform: ping
  name: Kurt Tunnel
  host: 192.168.88.1
  count: 2

- platform: ping
  name: internet_reachability
  host: 1.1.1.1
  count: 3
  scan_interval: 10

- platform: template
  sensors:
    # On if both backups < 10 minutes ago
    backups_complete:
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states('sensor.last_vps_backup_completed'))) < 600 and (as_timestamp(now()) - as_timestamp(states('sensor.last_nuc_backup_completed'))) < 600 }}"
    water_heater_water_detector:
      device_class: moisture
      value_template: "{{ states('sensor.water_heater_water_detector_alarm_level') == '254' }}"
