#- platform: generic
#  still_image_url: !secret weather_url
#  name: Weather

# Updating this with cronjob
- platform: local_file
  file_path: /tmp/radar.gif
  name: Weather Radar

- platform: local_file
  file_path: /config/images/mail_today.gif
  name: mail_usps

#- platform: mjpeg
#  mjpeg_url: http://10.0.0.26:8080/?action=stream
#  name: Outdoor

#- platform: ffmpeg
#  input: /opt/nodered/garden_timelapse/garden_timelapse.mp4
#  name: Garden Timelapse
#  extra_arguments: '-q:v 2 -r 3'

#- platform: ffmpeg
#  input: /opt/nodered/front_timelapse/front_timelapse.mp4
#  name: Front Timelapse
#  extra_arguments: '-q:v 2 -r 3'

#- platform: ffmpeg
#  input: /opt/nodered/side_timelapse/side_timelapse.mp4
#  name: Side Timelapse
#  extra_arguments: '-q:v 2 -r 3'
