homeassistant:
  name: Home
  external_url: !secret external_url
  internal_url: http://assistlocal
  elevation: !secret elevation
  unit_system: imperial
  latitude: !secret home_lat
  longitude: !secret home_long
  time_zone: America/Chicago
  customize: !include customize.yaml
  packages:
    alexa: !include packages/alexa.yaml
    aarlo: !include packages/aarlo.yaml
    aquarium: !include packages/aquarium.yaml
    covid: !include packages/covid.yaml
    #fingerprint: !include packages/fingerprint.yaml
    garage_door: !include packages/garage_door.yaml
    gate: !include packages/mom_and_dad_gate.yaml
    grill: !include packages/grill.yaml
    hass_update_check: !include packages/hass_update_check.yaml
    magic_cube: !include packages/magic_cube.yaml
    irrigation: !include packages/irrigation.yaml
    reminders: !include packages/reminders.yaml
    ups_monitoring: !include packages/ups_monitor.yaml
    vacuum: !include packages/vacuum.yaml
    zoom: !include packages/zoom.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.0.1.0/24
  allowlist_external_dirs:
    - "/tmp"

alexa: !include alexa.yaml

automation: !include automations.yaml

binary_sensor: !include binary_sensor.yaml

camera: !include camera.yaml

circadian_lighting:
  # Set manual sunrise/sunset for aquarium brightness
  sunrise_time: "09:00:00"
  sunset_time: "20:00:00"
  interval: 300
  transition: 10

config:

# Watch for nginx proxy manager changes
folder_watcher:
  - folder: /tmp
    use_polling: True
    patterns:
      - 'database.sqlite'

monitor_docker:
  #scan_interval: 60
  monitored_conditions:
    - state
  #switchname: 'docker_{name}'
  rename:
    adguard: "AdGuard"
    apcupsd_650: "APCUPSD 650"
    apcupsd_950: "APCUPSD 950"
    appdaemon: "Appdaemon"
    configurator: "VSCode"
    esphome: "ESPHome"
    grafana: "Grafana"
    influxdb: "InfluxDB"
    librespeed: "Speedtest"
    mariadb: "MariaDB"
    mosquitto: "Mosquitto"
    nodered: "Node-RED"
    plex: "Plex"
    portainer: "Portainer"
    thermopro_mqtt: "Grill Monitor"
    thermostat_api_server: "Thermostat API Server"
    vscode: "VSCode"
    watchtower: "Watchtower"
    zwavejs: "Zwave-JS"

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

group: !include group.yaml

history:

homekit: !include homekit.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.21.0.0/24 # Nginx Proxy Manager
  server_port: 8123

influxdb:
  host: 10.0.1.22
  exclude:
    entities:
      - binary_sensor.internet_reachability
      - binary_sensor.iss
      - sensor.aarlo_signal_strength_office
      - sensor.kitchen_timer_countdown
      - sensor.irrigation_time_remaining
      - sensor.last_boot
      - sensor.mail_updated
      - sensor.moon
      - sensor.thermostat_last_communication
    domains:
      - automation
      - alarm_panel
      - camera
      - group
      - media_player
      - notify
      - scene
      - script
      - shell_command
      - sun
      - zone
      - zwave

input_boolean: !include input_boolean.yaml

input_datetime: !include input_datetime.yaml

input_select: !include input_select.yaml

intent_script: !include intent_script.yaml

input_text: !include input_text.yaml

ios:
  push:
    categories:
      - name: Confirm
        identifier: "confirm"
        actions:
          - identifier: "confirm_unlock"
            title: "Confirm"
          - identifier: "ignore_unlock"
            title: "Ignore"

light:
  - platform: limitlessled
    bridges:
      - host: 10.0.0.47
        version: 5
        port: 8899
        groups:
        # big bulbs
        #- number: 1 
        #  type: rgbw
        #  name: Garage
        #  fade: on
        - number: 2
          type: rgbw
          name: aquarium_light
          fade: on
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_can_lights
      - light.kitchen_table_light
      - light.kitchen_sink_light
  - platform: group
    name: Master Bedroom Lamps
    entities:
      - light.andrew_nightstand_lamp
      - light.bethany_nightstand_lamp
  - platform: group
    name: Living Room Lamps
    entities:
      - light.living_room_lamp
      - light.living_room_lamp_2
  - platform: group
    name: Front Porch Lights
    entities:
      - light.front_porch_left
      - light.front_porch_right
  - platform: group
    name: Front Sconces
    entities:
      - light.front_sconce_left
      - light.front_sconce_right
  - platform: group
    name: Front House Lights
    entities:
      - light.front_sconces
      - light.front_porch_lights

logbook:

logger:
  #default: debug
  default: warn
  logs:
    homeassistant.core: debug
    # Start ZHA Debugging
    asyncio: debug
    homeassistant.components.zha: debug
    zigpy: debug
    bellows: debug
    zigpy_xbee: debug
    zigpy_deconz: debug
    zigpy_zigate: debug
    zigpy_cc: debug
    bellows.zigbee.application: debug
    bellows.ezsp: debug
    zigpy_deconz.zigbee.application: debug
    zigpy_deconz.api: debug
    zigpy_xbee.ap: debug
    zigpy_znp: debug
    zhaquirks: debug
    # End ZHA Debugging
    #custom_components.docker_monitor: debug
    #custom_components.alexa_media: debug
    #custom_components.localtuya: debug
    #homeassistant.components.webhook: debug
    #custom_components.mail_and_packages: debug
  filters:
    homeassistant.core:
      - ".*share-service-download-bucket.*" # Ring Video Updates
      - ".*camera.xiaomi_cloud_map_extractor.*" # Ring Video Updates

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: js
    - url: /hacsfiles/lovelace-hass-aarlo/hass-aarlo.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    #- url: /hacsfiles/custom-header/custom-header.js
    #  type: module
    - url: /hacsfiles/favicon-counter/favicon-counter.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/zha-network-visualization-card/zha-network-visualization-card.js
      type: module
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/ozw-network-visualization-card/ozw-network-visualization-card.js
      type: module
    - url: /hacsfiles/lovelace-text-input-row/lovelace-text-input-row.js
      type: module
    - url: /hacsfiles/uptime-card/uptime-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/flipdown-timer-card/flipdown-timer-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module

map:

mobile_app:

my:

netatmo:
  client_id: !secret netatmo_key
  client_secret: !secret netatmo_secret

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

panel_iframe:
  vscode:
    title: VS Code
    icon: mdi:wrench
    url: !secret vscode_url 
  plane_tracking:
    title: "Plane Tracking"
    icon: mdi:airplane
    url: !secret plane
  grafana:
    title: "Grafana"
    icon: mdi:chart-areaspline
    url: !secret grafana
  esphome:
    title: "ESPHome"
    icon: mdi:memory
    url: !secret esphome
  portainer:
    title: "Portainer"
    icon: mdi:ferry
    url: !secret portainer
  nodered:
    title: "Node-Red"
    icon: mdi:sitemap
    url: !secret nodered

plant:
  garden:
    sensors:
      moisture: sensor.miflora_moisture
      temperature: sensor.miflora_temperature
      conductivity: sensor.miflora_soil_conductivity
      brightness: sensor.miflora_illuminance
    min_moisture: 20
    max_moisture: 100

python_script:

readme:

recorder:
  db_url: mysql://homeassistant:homeassistant@10.0.1.22/homeassistant?charset=utf8
  purge_keep_days: 365
  exclude:
    entities:
      - automation.update_readme
      - automation.update_usps_mail_camera_path_on_hass_restart
      - automation.update_utilities_cost
      - automation.sync_cloudflare_cname_records
      - binary_sensor.internet_reachability
      - binary_sensor.gate_heading_comparison
      - binary_sensor.iss
      - script.zen30_led_color_change
      - sensor.aarlo_signal_strength_office
      - sensor.kitchen_timer_countdown
      - sensor.kitchen_next_timer
      - sensor.irrigation_time_remaining
      - sensor.last_boot
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.mail_updated
      - sensor.moon
      - sensor.network_in_eno1
      - sensor.network_out_eno1
      - sensor.roborock_s4_last_cleaned
      - sensor.circadian_values
      - sensor.thermostat_last_communication
      - sensor.weasel_last_seen
      - sensor.nuc_nuc_last_seen
      - sensor.it_c02xrkvwjg5j_last_seen
      - sensor.pixel_2_xl_last_seen
      - sensor.aneischvps_last_seen
    domains:
      #- automation
      #- alarm_panel
      - camera
      - group
      - media_player
      - notify
      - scene
      #- script
      #- shell_command
      - sun
      - zone
  include:
    entities:
      - group.trackers

rest_command: !include rest_command.yaml

samsungtv:
  - host: 10.0.1.51
    name: Living Room TV
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: 44:5c:e9:2e:51:0a

scene: !include scene.yaml

script: !include scripts.yaml

setter:

sensor: !include sensors.yaml

shell_command: !include shell_command.yaml

sonoff:
  username: !secret ewelink_user
  password: !secret ewelink_pass
  mode: local
  reload: always

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

stream:

sun:

switch: !include switches.yaml

system_health:

template: !include template.yaml

timer:
  kitchen_alexa:
    duration: "00:00:00"

wemo:
  discovery: false
  static:
    - 10.0.1.48

xbox:
  client_id: !secret xbox_id
  client_secret: !secret xbox_secret

zha:
  enable_quirks: true
  custom_quirks_path: /config/custom_zha_quirks/
  zigpy_config:
    network:
      channel: 11
      channels: [11]
      pan_id: 0x1A62
      extended_pan_id: "DD:DD:DD:DD:DD:DD:DD:DD"

zone:
  - name: Andrew Work
    latitude: !secret andrew_work_lat
    longitude: !secret andrew_work_long
    radius: 500
    icon: mdi:worker

  - name: Bethany Work
    latitude: !secret bethany_work_lat
    longitude: !secret bethany_work_long
    radius: 200
    icon: mdi:worker

  - name: Dan and Marilyn's
    latitude: !secret dan_lat
    longitude: !secret dan_long
    radius: 500
    icon: mdi:home-variant

  - name: Wayne and Lisa's
    latitude: !secret wayne_lat
    longitude: !secret wanye_long
    radius: 500
    icon: mdi:home-variant

  - name: Michael and Mandy's
    latitude: !secret michael_lat
    longitude: !secret michael_long
    radius: 500
    icon: mdi:home-variant

  - name: Kimberly and Travis'
    latitude: !secret travis_lat
    longitude: !secret travis_long
    radius: 500
    icon: mdi:home-variant
