homeassistant:
  name: Home
  elevation: !secret elevation
  unit_system: imperial
  latitude: !secret home_lat
  longitude: !secret home_long
  time_zone: America/Chicago
  customize: !include customize.yaml
  packages:
    gate_testing: !include packages/mom_and_dad_gate.yaml
    train: !include packages/train.yaml
    ups_monitoring: !include packages/ups_monitor.yaml
    #bus_time: !include packages/bus_time.yaml
    hass_update_check: !include packages/hass_update_check.yaml
    grill: !include packages/grill.yaml
    #voting: !include packages/voting.yaml
  auth_providers:
    - type: homeassistant

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password

alarm_control_panel:
  - platform: aarlo

alexa: !include alexa.yaml

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_pass
      url: "amazon.com"

automation: !include automation.yaml

binary_sensor: !include binary_sensor.yaml

camera: !include camera.yaml

# 5/21/2020 Fix Custom Header https://github.com/maykar/custom-header/issues/192
conversation:

climate:
  platform: radiotherm
  host:
    - 10.0.0.29
  hold_temp: True

config:

device_tracker:
  - platform: nmap_tracker
    home_interval: 10
    hosts: 
      - 10.0.1.13/32
      - 10.0.1.59/32

# https://github.com/aneisch/docker_monitor
docker_monitor:
#  containers:
#    - grafana
  # Interval is hard coded in __init__.py
  # scan_interval:
  #   seconds: 10

digital_ocean:
  access_token: !secret DO_token

fan: !include fans.yaml

frontend:
  themes: !include_dir_merge_named themes

group: !include group.yaml

history:

homekit: !include homekit.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  server_port: 8123
  #base_url: !secret hass_url

#ifttt:
#  key: !secret ifttt_key

influxdb:
  host: 10.0.1.22
  exclude:
    entities:
      - binary_sensor.internet_reachability
      - binary_sensor.iss
      - sensor.aarlo_signal_strength_office
      - sensor.dark_sky_icon
      - sensor.dark_sky_summary
      - sensor.kitchen_timer_countdown
      - sensor.last_boot
      - sensor.mail_updated
      - sensor.moon
    domains:
      - automation
      - alarm_panel
      - camera
      - group
      - media_player
      - notify
      - scene
      - script
      - shell_command
      - sun
      - zone
      - zwave

input_boolean: !include input_boolean.yaml

input_datetime: !include input_datetime.yaml

input_select: !include input_select.yaml

intent_script: !include intent_script.yaml

ios:

light:
  - platform: limitlessled
    bridges:
      - host: 10.0.0.47
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: master_bedroom
          fade: on
        - number: 2
          type: rgbw
          name: andrew_monitor_backlight
          fade: on
  - platform: group
    name: Master Bedroom Lamps
    entities:
      - light.andrew_nightstand_lamp
      - light.bethany_nightstand_lamp

logbook:

logger:
  default: warn
  logs:
    homeassistant.core: debug
    #custom_components.docker_monitor: debug
    homeassistant.components.webhook: debug

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/toggle-lock-entity-row/toggle-lock-entity-row.js
      type: js
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: js
    - url: /hacsfiles/lovelace-hass-aarlo/hass-aarlo.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: js
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: js
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/favicon-counter/favicon-counter.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module

map:

mobile_app:

netatmo:
  client_id: !secret netatmo_key
  client_secret: !secret netatmo_secret

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
#  - platform: alexa_media

owntracks:

panel_custom:
  # https://gist.github.com/AdamNaj/cbf4d792a22f443fe9d354e4dca4de00
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url 
  plane_tracking:
    title: 'Plane Tracking'
    icon: mdi:airplane
    url: !secret plane
  grafana:
    title: 'Grafana'
    icon: mdi:chart-areaspline
    url: !secret grafana
  esphome:
    title: 'ESPHome'
    icon: mdi:memory
    url: !secret esphome
  portainer:
    title: 'Portainer'
    icon: mdi:ferry
    url: !secret portainer
  nodered:
    title: 'Node-Red'
    icon: mdi:sitemap
    url: !secret nodered

person:
  - name: Andrew
    id: andrew
    device_trackers:
      - device_tracker.andrews_phone_nmap
      - device_tracker.owntracks_andrewworkphone
  - name: Bethany
    id: bethany
    device_trackers:
      - device_tracker.bethanys_iphone_nmap
      - device_tracker.bethany_s_iphone
      - device_tracker.owntracks_bethanyphone

#pi_hole:
#  host: '10.0.1.22:8000'

plant:
  garden:
    sensors:
      moisture: sensor.miflora_moisture
      temperature: sensor.miflora_temperature
      conductivity: sensor.miflora_soil_conductivity
      brightness: sensor.miflora_illuminance
    min_moisture: 20
    max_moisture: 100

#plex:
#  host: 10.0.1.22
#  token: !secret plex_token
#  media_player:
#    use_episode_art: false
#    show_all_controls: true

#proximity:
#  home:
#    devices:
#      - device_tracker.owntracks_andrewworkphone
#      - device_tracker.owntracks_bethanyphone
#      - device_tracker.bethanys_iphone
#    tolerance: 50
#    unit_of_measurement: mi

python_script:

readme:

recorder:
  purge_keep_days: 7
  exclude:
    entities:
      - binary_sensor.internet_reachability
      - binary_sensor.iss
      - sensor.aarlo_signal_strength_office
      - sensor.dark_sky_icon
      - sensor.dark_sky_summary
      - sensor.kitchen_timer_countdown
      - sensor.last_boot
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.mail_updated
      - sensor.moon
      - sensor.network_in_eno1
      - sensor.network_out_eno1
    domains:
      - automation
      - alarm_panel
      - camera
      - group
      - media_player
      - notify
      - scene
      - script
      - shell_command
      - sun
      - zone
      - zwave

rest_command: !include rest_command.yaml

scene: !include scene.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

shell_command: !include shell_command.yaml

#shopping_list:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

sun:

switch: !include switches.yaml

system_health:

#weather:
#  - platform: darksky
#    api_key: !secret darksky_api_key
#    mode: daily

zone:
  - name: Andrew Work
    latitude: !secret andrew_work_lat
    longitude: !secret andrew_work_long
    radius: 500
    icon: mdi:worker

  - name: Bethany Work
    latitude: !secret bethany_work_lat
    longitude: !secret bethany_work_long
    radius: 200
    icon: mdi:worker

  - name: Dan and Marilyn's
    latitude: !secret dan_lat
    longitude: !secret dan_long
    radius: 500
    icon: mdi:home-variant

  - name: Wayne and Lisa's
    latitude: !secret wayne_lat
    longitude: !secret wanye_long
    radius: 500
    icon: mdi:home-variant

  - name: Michael and Mandy's
    latitude: !secret michael_lat
    longitude: !secret michael_long
    radius: 500
    icon: mdi:home-variant

  - name: Kimberly and Travis'
    latitude: !secret travis_lat
    longitude: !secret travis_long
    radius: 500
    icon: mdi:home-variant

#zha:
#  usb_path: /dev/zigbee
#  radio_type: ti_cc
#  database_path: /config/.storage/zigbee.db

#zwave:
#  usb_path: /dev/zwave
