- platform: template
  fans:
    # Dummy for HomeKit
    master_bedroom_ceiling_fan:
      friendly_name: "Master Bedroom Ceiling Fan"
      availability_template: "{{ states.fan.master_bedroom_ceiling_fan_level.state in ['on','off'] }}"
      value_template: >
        {% if states.fan.master_bedroom_ceiling_fan_level.state not in ['on','off'] %}
          off
        {% else %}
          {{ states.fan.master_bedroom_ceiling_fan_level.state }}
        {% endif %}
      turn_on:
        service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_ceiling_fan_level
      turn_off:
        service: fan.turn_off
        data:
          entity_id: fan.master_bedroom_ceiling_fan_level
