sensor:
  - name: "Last NUC Backup Completed"
    state_topic: "sensor/rsync_nuc"
    value_template: "{{ strptime(value_json.timestamp, '%Y-%m-%d %H:%M:%S') }}"

  - name: "Last VPS Backup Completed"
    state_topic: "sensor/rsync_vps"
    value_template: "{{ strptime(value_json.timestamp, '%Y-%m-%d %H:%M:%S') }}"