- platform: moon

- platform: uptime

#- platform: arlo

#- platform: aarlo
#  monitored_conditions:
#  - last_capture
#  - total_cameras
#  - battery_level
#  - captured_today
#  - signal_strength

- platform: systemmonitor
  scan_interval:
    seconds: 60
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: network_in
      arg: eno1
    - type: network_out
      arg: eno1
    - type: last_boot
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: mqtt
  state_topic: "sensor/rsync_nuc"
  name: "Last NUC Backup Completed"
  value_template: "{{ strptime(value_json.timestamp, '%Y-%m-%d %H:%M:%S') }}"

- platform: mqtt
  state_topic: "sensor/rsync_vps"
  name: "Last VPS Backup Completed"
  value_template: "{{ strptime(value_json.timestamp, '%Y-%m-%d %H:%M:%S') }}"

# Measure wifi speed from macbook to NUC
# uses librespeed container on NUC and librespeed-cli on mac
- platform: mqtt
  state_topic: "sensor/home_wifi"
  name: "Home Wifi Speedtest"
  value_template: "{{ value_json.download }}"
  json_attributes_topic: "sensor/home_wifi"

####################
# BEGIN SONOFF POW #
####################
- platform: mqtt
  name: Sonoff Pow Yesterday Energy
  unit_of_measurement: "kWh"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Yesterday }}"

- platform: mqtt
  name: Sonoff Pow Today Energy
  unit_of_measurement: "kWh"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Today }}"

- platform: mqtt
  name: Sonoff Pow Current
  unit_of_measurement: "Amps"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Current }}"

- platform: mqtt
  name: Sonoff Pow Power
  unit_of_measurement: "Watts"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Power }}"

- platform: mqtt
  name: Rain Total
  unit_of_measurement: "in"
  state_topic: "sensor/rtl_433/rain_in"

- platform: mqtt
  name: Rain Rate
  unit_of_measurement: "in/h"
  state_topic: "sensor/rtl_433/rain_rate_in_h"

- platform: mqtt
  name: Compost External Temperature
  unit_of_measurement: "°F"
  state_topic: "sensor/rtl_433/temperature_F"

- platform: mqtt
  name: Compost External Humidity
  unit_of_measurement: "%"
  state_topic: "sensor/rtl_433/humidity"

- platform: mqtt
  name: Compost Internal Temperature
  unit_of_measurement: "°F"
  state_topic: "sensor/rtl_433/temperature_1_F"

###################
# MQTT THERMOSTAT #
###################

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Temperature"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.rt }}"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.rh }}"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Operating Mode"
  value_template: "{{ value_json.mode }}"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Fan Mode"
  value_template: "{{ value_json.fan }}"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat State"
  value_template: >
    {% if value_json.coolicon == 'on' %}
      Cooling
    {% elif value_json.heaticon == 'on' %}
      Heating
    {% elif value_json.fanicon == 'on' %}
      Idle Fan
    {% elif value_json.coolicon == 'off' and value_json.heaticon == 'off' and value_json.fanicon == 'off' %}
      Idle
    {% else %}
      Unknown
    {% endif %}

- platform: mqtt
  state_topic: "sensor/thermostat"
  unit_of_measurement: "°F"
  name: "Thermostat Setpoint"
  value_template: >
    {% if value_json.mode == 'cool' %}
      {{ value_json.clsp }}
    {% elif value_json.mode == 'heat' %}
      {{ value_json.htsp }}
    {% endif %}

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Fan Status"
  value_template: "{{ value_json.fanicon }}"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Hold"
  value_template: "{{ value_json.hold }}"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Filter Hours Remain"
  value_template: "{{ value_json.filtrlvl }}"
  unit_of_measurement: "h"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Outdoor Coil Temperature"
  value_template: "{{ value_json.oducoiltmp }}"
  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Outdoor Ambient Temperature"
  value_template: "{{ value_json.oat }}"
  unit_of_measurement: "°F"
  
- platform: mqtt
  state_topic: "sensor/thermostat"
  name: "Thermostat Indoor CFM"
  value_template: "{{ value_json.iducfm }}"
  unit_of_measurement: "cfm"

- platform: history_stats
  name: ac_runtime_today_cool
  entity_id: sensor.thermostat_state
  state: "Cooling"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: ac_runtime_today_heat
  entity_id: sensor.thermostat_state
  state: "Heating"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: ac_runtime_yesterday_cool
  entity_id: sensor.thermostat_state
  state: "Cooling"
  type: time
  end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  duration:
    hours: 24

- platform: history_stats
  name: ac_runtime_yesterday_heat
  entity_id: sensor.thermostat_state
  state: "Heating"
  type: time
  end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  duration:
    hours: 24

- platform: command_line
  name: CPU Temperature
  command: "echo $(($(cat /sys/class/thermal/thermal_zone0/temp)/1000))"
  unit_of_measurement: "°F"
  value_template: "{{ ((value | int) * 9 / 5) + 32 | round(1) }}"


#############
# TEMPLATES #
#############

- platform: template
  sensors:
    kitchen_timer_countdown:
      value_template: ""
      icon_template: "mdi:timer"

    kitchen_all_timers:
      friendly_name: "All Kitchen Timers"
      value_template: "{{ state_attr('sensor.kitchen_next_timer','sorted_active') | from_json | length }}"
      attribute_templates:
        timers_ending: >
          {% set ns = namespace(timers=[]) %}
          {% for i in (state_attr('sensor.kitchen_next_timer','sorted_active') | from_json) -%}
          {% set last_update = as_timestamp(state_attr('sensor.kitchen_next_timer','last_updated')) -%}
          {% set remain = i[1]['remainingTime']/1000 -%}
          {% set end_epoch = remain + last_update -%}
          {% set end_time = end_epoch | timestamp_custom('%Y-%m-%dT%H:%M:%S', True) -%}
          {% set ns.timers = ns.timers + [end_time] %}
          {% endfor %}
          {{ ns.timers }}

    ac_runtime_today:
      friendly_name: "AC Runtime Today"
      unit_of_measurement: "h"
      value_template: "{{ (states('sensor.ac_runtime_today_cool') | float + states('sensor.ac_runtime_today_heat') | float) }}"
      attribute_templates:
        value: "{{ (60 * (states('sensor.ac_runtime_today_cool') | float + states('sensor.ac_runtime_today_heat') | float)) | int }}m"

    ac_runtime_yesterday:
      friendly_name: "AC Runtime Today"
      unit_of_measurement: "h"
      value_template: "{{ (states('sensor.ac_runtime_yesterday_cool') | float + states('sensor.ac_runtime_yesterday_heat') | float) }}"
      attribute_templates:
        value: "{{ (60 * (states('sensor.ac_runtime_yesterday_cool') | float + states('sensor.ac_runtime_yesterday_heat') | float)) | int }}m"

    netatmo_home_rain_sum_rain_today_inches:
      friendly_name: Rainfall Today
      unit_of_measurement: in
      value_template: "{{ '%.2f'%((states('sensor.netatmo_home_home_rain_sum_rain_24') | float) / 25.4) }}"
      icon_template: >
        {% set amount = (states('sensor.netatmo_home_rain_sum_rain_today_inches') | float) %}
        {% if amount >= 0.50 %}
          mdi:weather-pouring
        {% elif amount > 0.00 and amount < 0.50 %}
          mdi:weather-rainy
        {% else %}
          mdi:cloud-outline
        {% endif %}

    netatmo_home_rain_sum_rain_last_hour_inches:
      friendly_name: Rainfall Last 1 Hour
      unit_of_measurement: in
      value_template: "{{ '%.2f'%((states('sensor.netatmo_home_home_rain_sum_rain_1') | float) / 25.4) }}"
      icon_template: >
        {% set amount = (states('sensor.netatmo_home_rain_sum_rain_last_hour_inches') | float) %}
        {% if amount >= 0.50 %}
          mdi:weather-pouring
        {% elif amount > 0.00 and amount < 0.50 %}
          mdi:weather-rainy
        {% else %}
          mdi:cloud-outline
        {% endif %}

    sonoff_pow_today_cost:
      friendly_name: Sonoff Pow Today Cost
      unit_of_measurement: "$"
      value_template: "{{ states('sensor.sonoff_pow_today_energy')  | multiply(0.1123) | round(2) }}"

    sonoff_pow_yesterday_cost:
      friendly_name: Sonoff Pow Yesterday Cost
      unit_of_measurement: "$"
      value_template: "{{ states('sensor.sonoff_pow_yesterday_energy')  | multiply(0.1123) | round(2) }}"

    mail_deliveries_message:
      friendly_name: "Deliveries Summary"
      value_template: > 
        {# Deliveries Sentence #}
          {% macro deliveries_sentence() -%}
                {%- if states('sensor.mail_usps_mail')|int == 0 -%}
                  No
                {%- else -%}
                  {{states('sensor.mail_usps_mail')|int}}
                {%- endif -%}
              {{' '}} 
                {%- if states('sensor.mail_usps_mail')|int <= 1 -%}
                  mail
                {%- else -%}
                  pieces of mail
                {%- endif -%}
              {{' '}}will be delivered.{{' '}} 
                {%- if states('sensor.mail_packages_in_transit')|int == 0 -%}
                  No
                {%- else -%}
                  {{states('sensor.mail_packages_in_transit')|int}}
                {%- endif -%}
              {{' '}} 
                {%- if states('sensor.mail_packages_in_transit')|int == 1 -%}
                  package is
                {%- else -%}
                  packages are
                {%- endif -%}
              {{' '}}in transit.{{' '}}
          {%- endmacro %}
        {{deliveries_sentence()}}
    nws_temperature:
      friendly_name: "Temperature"
      unit_of_measurement: "°F"
      value_template: "{{ state_attr('weather.kcll_daynight', 'temperature') }}"
    nws_humidity:
      friendly_name: "Humidity"
      unit_of_measurement: "%"
      icon_template: mdi:water-percent
      value_template: "{{ state_attr('weather.kcll_daynight', 'humidity') }}"
    nws_pressure:
      friendly_name: "Pressure"
      unit_of_measurement: "mbar"
      value_template: "{{ state_attr('weather.kcll_daynight', 'pressure') }}"
    nws_wind_speed:
      friendly_name: "Wind Speed"
      unit_of_measurement: "mph"
      icon_template: mdi:weather-windy
      value_template: "{{ state_attr('weather.kcll_daynight', 'wind_speed') }}"
    nws_precip_probability:
      friendly_name: "Percent Chance of Rain"
      unit_of_measurement: "%"
      icon_template: mdi:water-percent
      value_template: >
        {% if state_attr('weather.kcll_daynight', 'forecast')[0]['daytime'] == True %}
          {{ state_attr('weather.kcll_daynight', 'forecast')[0]['precipitation_probability'] }}
        {% else %}
          {{ state_attr('weather.kcll_daynight', 'forecast')[1]['precipitation_probability'] }}
        {% endif %}
