- platform: orvibo
  switches:
  -  host: 10.0.0.21
     name: master_bedroom_sound_machine

- platform: broadlink
  host: 10.0.0.11
  mac: b4:43:0d:ae:61:36
  type:  sp2
  friendly_name: 'Entertainment Center Lights'

#- platform : mqtt
#  name: "Stupid Red Light"
#  state_topic: "light/red_light"
#  command_topic: "light/red_light"
#  payload_on: "ON"
#  payload_off: "OFF"
#  retain: true

- platform : mqtt
  name: "Christmas Tree"
  state_topic: "stat/sonoff_pow_1/POWER"
  command_topic: "cmnd/sonoff_pow_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform: wake_on_lan
  name: "NAS"
  mac: "e8:fc:af:e6:22:26"
  host: 10.0.1.20
  turn_off:
      service: shell_command.nas_poweroff

- platform: template
  switches:
    tv:
      value_template: "{{ states.binary_sensor.power_plug_2_power.state }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.tv_remote_power
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.tv_remote_power

#- platform: command_line
#  scan_interval: 60
#  switches:
#    pihole_switch:
#      command_on: "curl -X GET 'http://localhost:8000/admin/api.php?enable&auth='"
#      command_off: "curl -X GET 'http://localhost:8000/admin/api.php?disable=3600&auth='"
#      command_state: "curl -X GET 'http://localhost:8000/admin/api.php?status'"
#      value_template: "{{ value_json.status == 'enabled' }}"
