#- platform: command_line
#  switches:
#    living_room_christmas:
#      oncmd: 'curl -s http://10.0.1.13:82/cgi-bin/toggle.cgi > /dev/null &'
#      offcmd: 'curl -s http://10.0.1.13:82/cgi-bin/toggle.cgi > /dev/null &' 


- platform: orvibo
  discovery: false
  switches:
  -  host: 10.0.1.11
     name: living_room_lamp
  -  host: 10.0.1.21
     name: andrew_sound_machine


- platform : mqtt
  name: "Andrew Ceiling Fan"
  state_topic: "stat/sonoff_fan/POWER"
  command_topic: "cmnd/sonoff_fan/POWER"
  payload_on: "On"
  payload_off: "Off"
  optimistic: false
  retain: true

- platform : mqtt
  name: "Christmas Lights"
  state_topic: "stat/sonoff_2/POWER"
  command_topic: "cmnd/sonoff_2/POWER"
  payload_on: "On"
  payload_off: "Off"
  optimistic: false
  retain: true

- platform : mqtt
  name: "Sonoff Pow"
  state_topic: "stat/sonoff_pow_1/POWER"
  command_topic: "cmnd/sonoff_pow_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform: wake_on_lan
  name: "NAS" 
  mac_address: "e8:fc:af:e6:22:26"
  host: 10.0.1.20
