- platform: orvibo
  switches:
  -  host: 10.0.1.11
     name: orvibo_1
  -  host: 10.0.1.21
     name: master_bedroom_sound_machine

- platform: broadlink
  host: 10.0.1.30
  mac: b4:43:0d:ae:61:36
  type:  sp2
  friendly_name: 'Entertainment Center Lights'

#- platform : mqtt
#  name: "Stupid Red Light"
#  state_topic: "light/red_light"
#  command_topic: "light/red_light"
#  payload_on: "ON"
#  payload_off: "OFF"
#  retain: true

- platform : mqtt
  name: "Christmas Tree"
  state_topic: "stat/sonoff_pow_1/POWER"
  command_topic: "cmnd/sonoff_pow_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform: wake_on_lan
  name: "NAS"
  mac_address: "e8:fc:af:e6:22:26"
  host: 10.0.1.20
  turn_off:
      service: shell_command.nas_poweroff
