#sensors.yaml
domain_name: domain.fako.com Certificate Expiry
domain: domain.fako.com
domain_2_name: domain2.fako.com Certificate Expiry
domain_2: domain2.fako.com
darksky_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
usps_username: user
usps_key: key
fedex_username: user
fedex_password: key
ups_username: user
ups_password: key
17track_user: user
17track_pass: pass

#configuration.yaml
home_lat: 00.00
home_long: 00.00
andrew_work_lat: 00.00
andrew_work_long: 00.00
bethany_work_lat: 00.00
bethany_work_long: 00.00
dan_lat: 00.00
dan_long: 00.00
wayne_lat: 00.00
wanye_long: 00.00
michael_lat: 00.00
michael_long: 00.00
travis_lat: 00.00
travis_long: 00.00
plane: https://fako.com:30053/
nodered: https://fakeo.com:4433/
homegraph: NOT_AN_API_KEY
grafana: https://fakeo.com:777/dashboard/db/home-assistant
esphome: https://my.domain.me/esphome
api_password: key
owntracks_user: user
owntracks_password: key
plex_token: token
plex_user: user
plex_password: password
amazon_email: EMAIL@FAKO.COM
amazon_pass: PASSWORD
spotify_client_id: id
spotify_client_secret: secret
tile_user: user
tile_password: password
pushbullet_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
pushover_api_key: XXXXXXXXXXXXXXXXXXXXXXX
pushover_user_key: XXXXXXXXXXXXXXXXXXXX
vapid_pub_key: really_public_key
vapid_prv_key: really_private_key
vapid_email: fake_email@fake.com
influx_user: user
influx_password: password
ifttt_key: XXXXXXXXXXXX
yahoo_woeid: XXXXXXXXXX
alexa_client_id: PHONY
alexa_client_secret: PHONY
haveibeenpwned_1: EMAIL
haveibeenpwned_2: EMAIL
haveibeenpwned_3: EMAIL
haveibeenpwned_4: EMAIL
haveibeenpwned_5: EMAIL
haveibeenpwned_6: EMAIL
netatmo_key: KEY
netatmo_secret: SECRET
netatmo_user: FAKE@EMAIL.COM
netatmo_pass: PASS
netatmo_lat_ne: 31
netatmo_lon_ne: -92
netatmo_lat_sw: 31
netatmo_lon_sw: -96
DO_token: TOKEN
DO_host: HOST
rtorrent: 'https://myuser:reallylegitpassword@reallyfake.com:443/RPC'
hacs_token: lolyeahright

#camera.yaml
weather_url: https://fako.com/weather
arlo_username: user@fako.com
arlo_password: key

#groups.yaml

#ui-lovelace.yaml
alarm_panel_1: alarm_panel.fake1
alarm_panel_2: alarm_panel.fake2
windy_url: https://embed.windy.com/embed2.html?rain
domain_expiry: sensor.domainfakocom
domain_2_expiry: sensor.domain2fakocom

#automation.yaml
gate_webhook_id: SECRET_URL
alexa_timer_webhook_id: SECRET_URL
