#sensors.yaml
domain_2_name: domain2.fako.com Certificate Expiry
domain_2: domain2.fako.com
darksky_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
usps_username: user
usps_key: key
fedex_username: user
fedex_password: key
ups_username: user
ups_password: key
17track_user: user
17track_pass: password

#configuration.yaml
hass_url: https://not_really_it.com
elevation: 60000
home_lat: 00.00
home_long: 00.00
andrew_work_lat: 00.00
andrew_work_long: 00.00
bethany_work_lat: 00.00
bethany_work_long: 00.00
configurator_url: https://www.home-assistant.io/docs/ecosystem/hass-configurator/
vscode_url: https://community.home-assistant.io/t/install-vscode-visual-studio-code-as-a-separate-docker-container/166007/27
dan_lat: 00.00
dan_long: 00.00
external_url: https://google.com
github_recipes_webhook: lolsecret
wayne_lat: 00.00
wanye_long: 00.00
michael_lat: 00.00
michael_long: 00.00
travis_lat: 00.00
travis_long: 00.00
plane: https://en.wikipedia.org/wiki/Automatic_dependent_surveillance_%E2%80%93_broadcast
plane2: https://en.wikipedia.org/wiki/Automatic_dependent_surveillance_%E2%80%93_broadcast
nodered: https://nodered.org
grafana: https://grafana.com
esphome: https://esphome.io
portainer: https://www.portainer.io
api_password: key
owntracks_user: user
owntracks_password: key
plex_token: token
plex_user: user
plex_password: password
openweather: API_KEY
amazon_email: EMAIL@FAKO.COM
amazon_pass: PASSWORD
spotify_client_id: id
spotify_client_secret: secret
tile_user: user
tile_password: password
pushbullet_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
pushover_api_key: XXXXXXXXXXXXXXXXXXXXXXX
pushover_user_key: XXXXXXXXXXXXXXXXXXXX
vapid_pub_key: really_public_key
vapid_prv_key: really_private_key
vapid_email: fake_email@fake.com
influx_user: user
influx_password: password
ifttt_key: XXXXXXXXXXXX
yahoo_woeid: XXXXXXXXXX
alexa_client_id: PHONY
alexa_client_secret: PHONY
haveibeenpwned_1: EMAIL
haveibeenpwned_2: EMAIL
haveibeenpwned_3: EMAIL
haveibeenpwned_4: EMAIL
haveibeenpwned_5: EMAIL
haveibeenpwned_6: EMAIL
netatmo_key: KEY
netatmo_secret: SECRET
netatmo_lat_ne: 31
netatmo_lon_ne: -92
netatmo_lat_sw: 31
netatmo_lon_sw: -96
DO_token: TOKEN
DO_host: HOST
rtorrent: 'https://myuser:reallylegitpassword@reallyfake.com:443/RPC'
hacs_token: lolyeahright
roborock_token: d41d8cd98f00b204e4400998ec111111
utilities_curl_summary: "exit"
utilities_curl_daily: "exit"
utilities_curl_realtime: "exit"
xbox_id: 1
xbox_secret: s
zoom_webhook: zoomzoom

#camera.yaml
weather_url: https://fako.com/weather
arlo_username: user@fako.com
arlo_password: key

#groups.yaml

#ui-lovelace.yaml
alarm_panel_1: alarm_panel.fake1
alarm_panel_2: alarm_panel.fake2
windy_url: https://embed.windy.com/embed2.html?rain
domain_1_expiry_sensor: sensor.domainfakocom
domain_2_expiry_sensor: sensor.domain2fakocom

#automation.yaml
gate_webhook_id: SECRET_URL
mom_and_dad_garage_webhook_id: SECRET_URL
github_token: GITHUB_KEY
panic_script_webhook: somethingsecret
# need to full url with secret hook for pushover
panic_script_webhook_full: https://my-actual-domain.rocks/api/webhook/somethingsecret

#packages
hass_github_action_webhook: SECRET
garage_image_url: https://FQDN/local/cameras/garage_latest.jpg
xiaomi_cloud_username: user
xiaomi_cloud_password: password
