#sensors.yaml
darksky_api_key: XXX
17track_user: XXX
17track_pass: XXX

#configuration.yaml
hass_url: XXX
elevation: XXX
home_lat: XXX
home_long: XXX
andrew_work_lat: XXX
andrew_work_long: XXX
bethany_work_lat: XXX
bethany_work_long: XXX
configurator_url: XXX
vscode_url: XXX
dan_lat: XXX
dan_long: XXX
external_url: XXX
github_recipes_webhook: XXX
homegraph: XXX
wayne_lat: XXX
wanye_long: XXX
michael_lat: XXX
michael_long: XXX
travis_lat: XXX
travis_long: XXX
plane: XXX
plane2: XXX
grafana: XXX
esphome: XXX
nodered: XXX
portainer: XXX
api_password: XXX
owntracks_user: XXX
owntracks_password: XXX
openweather: XXX
plex_token: XXX
plex_user: XXX
plex_password: XXX
spotify_client_id: XXX
spotify_client_secret: XXX
tile_user: XXX
tile_password: XXX
pushbullet_key: XXX
pushover_api_key: XXX
pushover_user_key: XXX
vapid_pub_key: XXX
vapid_prv_key: XXX
vapid_email: XXX
influx_user: XXX
influx_password: XXX
ifttt_key: XXX
alexa_client_id: XXX
alexa_client_secret: XXX
haveibeenpwned_1: XXX
haveibeenpwned_2: XXX
haveibeenpwned_3: XXX
haveibeenpwned_4: XXX
haveibeenpwned_5: XXX
haveibeenpwned_6: XXX
netatmo_key: XXX
netatmo_secret: XXX
netatmo_lat_ne: XXX
netatmo_lon_ne: XXX
netatmo_lat_sw: XXX
netatmo_lon_sw: XXX
DO_token: XXX
DO_host: XXX
hacs_token: XXX
roborock_token: XXX
xbox_id: XXX
xbox_secret: XXX

#camera.yaml
weather_url: XXX
arlo_username: XXX
arlo_password: XXX

#groups.yaml

#ui-lovelace.yaml
windy_url: XXX
alarm_panel_1: XXX
alarm_panel_2: XXX

#automation.yaml
# https: XXX
gate_webhook_id: XXX
mom_and_dad_garage_webhook_id: XXX
github_token: XXX
panic_script_webhook: XXX
# need to full url with secret hook for pushover
panic_script_webhook_full: XXX

#packages
hass_github_action_webhook: XXX
garage_image_url: XXX
xiaomi_cloud_username: XXX
xiaomi_cloud_password: XXX