custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  chevrons: false
  hide_tabs: '{% if is_state("switch.docker_thermopro_mqtt", "off") %}7{% endif %}'
  tab_indicator_color: 'rgb(214, 122, 127)'
  footer_mode: '{% if "Pixel 2" in userAgent %}true{% else %}false{% endif %}'

swipe_nav:
  swipe_animate: fade

views: !include_dir_list ui-lovelace/

preload:
  - markdown
  - entity-filter
  - config-template-card
