resources:
  - url: /community_plugin/toggle-lock-entity-row/toggle-lock-entity-row.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/lovelace-gui-sandbox/gui-sandbox.js
    type: module
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /community_plugin/favicon-counter/favicon-counter.js
    type: module

custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  chevrons: false
  hide_tabs: '{% if is_state("switch.docker_thermopro_mqtt", "off") %}7{% endif %}'
  tab_indicator_color: 'rgb(214, 122, 127)'

swipe_nav:
  swipe: true
  swipe_animate: swipe
  swipe_amount: 5

views: !include_dir_list ui-lovelace/

