resources:
  - url: /community_plugin/toggle-lock-entity-row/toggle-lock-entity-row.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/lovelace-gui-sandbox/gui-sandbox.js
    type: module
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module

cch:
  options: show
  swipe: true
  swipe_animate: swipe
  swipe_amount: 5

#views: !include_dir_list ui-lovelace/
views:
  - !include ui-lovelace/01-home.yaml
  - !include ui-lovelace/02-common.yaml
  - !include ui-lovelace/03-master.yaml
  - !include ui-lovelace/04-server.yaml
  - !include ui-lovelace/05-gate.yaml
  - !include ui-lovelace/07-elements.yaml
  #- !include ui-lovelace/06-timelapse.yaml
