substitutions:
  name: andrew_desk_button
  friendly_name: "Andrew Desk Button"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin: D3
    id: button
    filters:
      - invert:
      # - delayed_on: 100ms
      # - delayed_off: 100ms
    on_click:
      min_length: 500ms
      max_length: 3000ms
      then:
        - binary_sensor.template.publish:
            id: single_press
            state: ON
        - delay: 1s
        - binary_sensor.template.publish:
            id: single_press
            state: OFF
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - binary_sensor.template.publish:
            id: double_press
            state: ON 
        - delay: 1s
        - binary_sensor.template.publish:
            id: double_press
            state: OFF
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
      then:
        - binary_sensor.template.publish:
            id: triple_press
            state: ON 
        - delay: 1s
        - binary_sensor.template.publish:
            id: triple_press
            state: OFF
  - platform: template
    id: single_press
    name: "${friendly_name} Single"
  - platform: template
    id: double_press
    name: "${friendly_name} Double"
  - platform: template
    id: triple_press
    name: "${friendly_name} Triple"
    
switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"
