substitutions:
  name: andrew_desk_keyboard_tray
  friendly_name: "Andrew Desk Keyboard Tray"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

sensor:
  # Read the sensor and pass to template to validate
  - platform: ultrasonic
    id: "ultrasonic_read"
    trigger_pin: D1
    echo_pin: D2
    accuracy_decimals: 5
    update_interval: 1s

  # Validate reading and then pass to binary
  - platform: template
    id: "ultrasonic_smoothed"
    lambda: |-
      if (id(ultrasonic_read).state > 0.2000 && id(ultrasonic_read).state < 0.6500) {
        return id(ultrasonic_read).state; 
      } else {
        return {};
      }
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 2

binary_sensor:
  - platform: template
    name: "${friendly_name}"
    device_class: opening
    lambda: if (id(ultrasonic_smoothed).state > 0.31) return true; else return false;