substitutions:
  name: andrew_desk_button
  friendly_name: "Andrew Desk Button"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin: D3
    name: "${friendly_name}"
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms