esphome:
  name: andrew_desk_button
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin: D3
    name: "Andrew Desk Button"
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms

sensor:
  - platform: uptime
    name: "Andrew Desk Button Uptime"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Andrew Desk Button IP Address"