substitutions:
  name: backyard_camera
  friendly_name: "Backyard Camera"

esphome:
  name: ${name}
  platform: ESP32
  board: esp32dev


<<: !include common.yaml
<<: !include midnight_reboot.yaml

esp32_ble_tracker:

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: "${friendly_name}"
  resolution: 1024x768
  max_framerate: 1 fps
  idle_framerate: 0.1 fps

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: "${friendly_name}"
    
sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:34:C8
    temperature:
      name: "MiFlora Temperature"
    moisture:
      name: "MiFlora Moisture"
    illuminance:
      name: "MiFlora Illuminance"
    conductivity:
      name: "MiFlora Soil Conductivity"
    battery_level:
      name: "MiFlora Battery Level" 

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"