substitutions:
  name: bethany_desk_lamp
  friendly_name: "Bethany Desk Lamp"

esphome:
  name: "${name}"
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

<<: !include common.yaml

status_led:
  pin:
    number: GPIO04
    inverted: yes

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: lamp

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: lamp
    name: "${friendly_name}"
    output: relay