substitutions:
  name: christmas_fenas_village
  friendly_name: "Christmas Fena's Village"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml
  
switch:
  # GPIO output for relay
  - platform: gpio
    id: relay
    name: ${friendly_name}
    icon: "mdi:home-modern"
    pin:
      number: D1
      inverted: False