# Common settings to all my devices
wifi:
  ssid: "SSID"
  password: "WPA_KEY"

logger:

api:
  reboot_timeout: 0s

ota:
  safe_mode: True
  password: esphome_recovery

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
