# Common settings to all my devices
wifi:
  ssid: "SSID"
  password: !secret wifi_password

logger:
  level: DEBUG

api:
  #reboot_timeout: 0s
  encryption:
    key: !secret encryption_key

ota:
  safe_mode: True
  password: esphome_recovery

# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: "${friendly_name} IP Address"
