substitutions:
  name: compost
  friendly_name: "Compost Pile"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: "SSID"
  password: "WPA_KEY"
  manual_ip:
    static_ip: 10.0.0.55
    gateway: 10.0.1.1
    subnet: 255.255.254.0

#logger:

ota:
  safe_mode: True
  password: esphome_recovery

mqtt:
  broker: 10.0.1.22
  on_message:
    - topic: compost/cmnd/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: compost/cmnd/ota_mode
      payload: 'OFF'
      then:
        - deep_sleep.enter: deep_sleep_1
  
deep_sleep:
  id: deep_sleep_1
  run_duration: 5s
  sleep_duration: 60min

sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 5s