esphome:
  name: desk_drawer
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "SSID"
  password: "WPA_KEY"

binary_sensor:
  - platform: gpio
    pin: D8
    name: "Desk Keyboard Drawer"
    device_class: opening
    filters:
      #- delayed_on: 500ms
      #- delayed_off: 500ms
      
sensor:
  - platform: uptime
    name: "Desk Keyboard Drawer Uptime"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Desk Keyboard Drawer IP Address"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota: