substitutions:
  name: door_nfc
  friendly_name: "Door NFC"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini_pro

<<: !include common.yaml

pn532_i2c:
  update_interval: 1s
  on_tag:
    then:
    - text_sensor.template.publish:
        id: rfid_tag
        state: !lambda 'return x;'

text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag
    update_interval: 10s
    lambda: |-
      return {""};

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

# binary_sensor:
#   - platform: pn532
#     uid: !secret andrew_fitbit_id
#     name: "${friendly_name} Andrew's Fitbit"
    
switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"