substitutions:
  name: door_sensor_s2
  friendly_name: "Door Sensor S2"

esphome:
  name: ${name}

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: ESP-IDF

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: IO1
    name: "Front Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: IO2
    name: "Master Bedroom Exterior Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: 5
    name: "Back Porch Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: 6
    name: "Garage Interior Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: 7
    name: "Garage Exterior Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

  # GPIO output for relay
  - platform: gpio
    id: relay
    icon: "mdi:alarm-bell"
    name: "Attic Siren"
    pin:
      number: 8
      inverted: False
    on_turn_on:
      # Sound siren for max 5 minutes
      - delay: 300s
      - switch.turn_off: relay