esphome:
  name: door_sensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "SSID"
  password: "WPA_KEY"

binary_sensor:
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D1
    name: "Back Door"
    device_class: door

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D2
    name: "Front Door"
    device_class: door

sensor:
  - platform: uptime
    name: "Door Sensor Uptime"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Door Sensor IP Address"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota: