substitutions:
  name: door_sensor
  friendly_name: "Door Sensor"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

# See https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/ for
# allowable pins

binary_sensor:
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D1
    name: "D1"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D2
    name: "D2"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D5
    name: "D5"
    device_class: door
    filters:
      - delayed_on_off: 0.5s
      
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D6
    name: "D6"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D7
    name: "D7"
    device_class: door
    filters:
      - delayed_on_off: 0.5s

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"
