substitutions:
  name: door_sensor
  friendly_name: "Door Sensor"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

# See https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/ for
# allowable pins

binary_sensor:
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D1
    name: "Back Door"
    device_class: door

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D2
    name: "Front Door"
    device_class: door
    
sensor:
  - platform: uptime
    update_interval: 600s
    name: "${friendly_name} Uptime"

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"
