substitutions:
  name: esp_camera
  friendly_name: "ESP Camera"

esphome:
  name: ${name}
  platform: ESP32
  board: esp32dev

<<: !include common.yaml
#<<: !include midnight_reboot.yaml

esp32_ble_tracker:

ble_client:
  - mac_address: 80:30:DC:EB:B8:92
    id: scale
    on_connect:
      then:
        - lambda: ESP_LOGD("ble_client_lambda", "Connected to BLE device");

# ESP32-CAM
# esp32_camera:
#   external_clock:
#     pin: GPIO0
#     frequency: 20MHz
#   i2c_pins:
#     sda: GPIO26
#     scl: GPIO27
#   data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
#   vsync_pin: GPIO25
#   href_pin: GPIO23
#   pixel_clock_pin: GPIO22
#   power_down_pin: GPIO32
#   name: "${friendly_name}"
#   resolution: 1024x768
#   max_framerate: 1 fps
#   idle_framerate: 0.1 fps

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: "${friendly_name}"

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:63:34:C8
    temperature:
      name: "MiFlora Temperature"
    moisture:
      name: "MiFlora Moisture"
    illuminance:
      name: "MiFlora Illuminance"
    conductivity:
      name: "MiFlora Soil Conductivity"
    battery_level:
      name: "MiFlora Battery Level" 
      
  - platform: ble_client
    ble_client_id: scale
    name: "1"
    service_uuid: '1800'
    characteristic_uuid: '2a00'
    update_interval: 2s
    accuracy_decimals: 5
    
  - platform: ble_client
    ble_client_id: scale
    name: "2"
    service_uuid: '1800'
    characteristic_uuid: '2a01'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "3"
    service_uuid: '1800'
    characteristic_uuid: '2a02'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "4"
    service_uuid: '1800'
    characteristic_uuid: '2a03'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "5"
    service_uuid: '1800'
    characteristic_uuid: '2a04'
    update_interval: 2s
    accuracy_decimals: 5
    
  - platform: ble_client
    ble_client_id: scale
    name: "6"
    service_uuid: '1801'
    characteristic_uuid: '2a05'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "7"
    service_uuid: 'FFF0'
    characteristic_uuid: 'FFF1'
    update_interval: 2s
    accuracy_decimals: 5
    
  - platform: ble_client
    ble_client_id: scale
    name: "8"
    service_uuid: 'FFF0'
    characteristic_uuid: 'FFF4'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "9"
    service_uuid: '180A'
    characteristic_uuid: '2A23'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "10"
    service_uuid: '180A'
    characteristic_uuid: '2A24'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "11"
    service_uuid: '180A'
    characteristic_uuid: '2A25'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "12"
    service_uuid: '180A'
    characteristic_uuid: '2A26'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "13"
    service_uuid: '180A'
    characteristic_uuid: '2A27'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "14"
    service_uuid: '180A'
    characteristic_uuid: '2A28'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "15"
    service_uuid: '180A'
    characteristic_uuid: '2A29'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "16"
    service_uuid: '180A'
    characteristic_uuid: '2A2A'
    update_interval: 2s
    accuracy_decimals: 5

  - platform: ble_client
    ble_client_id: scale
    name: "17"
    service_uuid: '180A'
    characteristic_uuid: '2A50'
    update_interval: 2s
    accuracy_decimals: 5

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"