substitutions:
  name: esp_camera
  friendly_name: "ESP Camera"

esphome:
  name: ${name}
  platform: ESP32
  board: esp32dev

<<: !include common.yaml
<<: !include midnight_reboot.yaml

esp32_ble_beacon:
  type: iBeacon
  uuid: '33d723f1-621e-68a5-59a0-8d15e3992d56'

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: "${friendly_name}"
  resolution: 1024x768
  max_framerate: 5 fps
  idle_framerate: 0.05 fps

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: "${friendly_name}"
    
switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"
