substitutions:
  name: ir_andrew_desk
  friendly_name: "IR Andrew Desk"
  carrier: 38kHz

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

remote_transmitter:
  pin:
    number: D3
    inverted: False
  carrier_duty_percent: 50%
  
remote_receiver:
  pin: 
    number: D4
    inverted: yes
    mode: INPUT_PULLUP
  dump: nec
  
switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

api:
  reboot_timeout: 0s
  encryption:
    key: !secret encryption_key

  services:
    - service: monitor_power
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF10EF # power on/off
            nbits: 32