substitutions:
  name: ir_candles
  friendly_name: "IR Candles"
  carrier: 38kHz

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

remote_transmitter:
  pin:
    number: D3
    inverted: False
  carrier_duty_percent: 50%
  
remote_receiver:
  pin: 
    number: D4
    inverted: yes
    mode: INPUT_PULLUP
  dump: nec
  
switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

api:
  reboot_timeout: 0s
  encryption:
    key: !secret encryption_key

# Candles are "GenSwin Waterproof Outdoor Flameless Candles with Remote Timer" https://www.amazon.com/gp/product/B08V89ZJ93
# but this probably works with most "generic" LED candles w/ IR remote. 
  services:
    - service: candles_on
      then:
        - remote_transmitter.transmit_nec:
            address: 0xFF00
            command: 0xFE01
            repeat:
              times: 3
              wait_time: 0.2s

    - service: candles_off
      then:
        - remote_transmitter.transmit_nec:
            address: 0xFF00
            command: 0xFF00
            repeat:
              times: 3
              wait_time: 0.2s

    - service: candles_brighter
      then:
        - remote_transmitter.transmit_nec:
            address: 0xFF00
            command: 0xEB14

    - service: candles_dimmer
      then:
        - remote_transmitter.transmit_nec:
            address: 0xFF00
            command: 0xF10E

    - service: candles_light_mode
      then:
        - remote_transmitter.transmit_nec:
            address: 0xFF00
            command: 0xE916

    - service: candles_candle_mode
      then:
        - remote_transmitter.transmit_nec:
            address: 0xFF00
            command: 0xF20D