substitutions:
  name: test
  friendly_name: "Kitchen Timer"

esphome:
  name: ili9341
  platform: ESP32
  board: nodemcu-32s

<<: !include common.yaml

text_sensor:
  - platform: homeassistant
    id: next_timer_countdown
    entity_id: sensor.kitchen_timer_countdown

spi: 
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

font:
  - file: "fonts/OpenSans-Regular.ttf"
    id: my_font
    size: 20

display:
  - platform: ili9341
    model: M5Stack
    update_interval: 1.0s
    cs_pin: 14
    dc_pin: 27
    led_pin: 32
    reset_pin: 33
    rotation: 0
    lambda: |-
      it.printf(0, 0, id(my_font), ili9341::WHITE, id(next_timer_countdown).state);