substitutions:
  name: master_bedroom
  friendly_name: "Master Bedroom"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini_pro

<<: !include common.yaml

sensor:
  # - platform: template
  #   id: "master_bed_smoothed"
  #   unit_of_measurement: kg
  #   #name: "${friendly_name} Bed Raw"
  #   lambda: |-
  #     if (id(master_bed_read).state > 600000 && id(master_bed_read).state < 710000) {
  #       return id(master_bed_read).state; 
  #     } else {
  #       return {};
  #     }
  #   update_interval: 1s
  #   filters:
  #     - sliding_window_moving_average:
  #         window_size: 10
  #         send_every: 5

  # - platform: hx711
  #   id: "master_bed_read"
  #   dout_pin: D2
  #   clk_pin: D3
  #   gain: 128
  #   update_interval: 5s

  - platform: dht
    model: DHT22
    pin: D4
    temperature:
      name: "${friendly_name} Temperature"
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: 60s

# binary_sensor:
#   - platform: template
#     name: "${friendly_name} Bed"
#     device_class: occupancy
#     lambda: if (id(master_bed_smoothed).state > 664000) return true; else return false;

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"