esphome:
  name: master_bedroom
  platform: ESP8266
  board: d1_mini_pro

<<: !include common.yaml

sensor:
  - platform: template
    id: "master_bed_smoothed"
    unit_of_measurement: kg
    name: "Master Bedroom Bed Raw"
    lambda: |-
      if (id(master_bed_read).state > 655000 && id(master_bed_read).state < 710000) {
        return id(master_bed_read).state; 
      } else {
        return {};
      }
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 5
  - platform: hx711
    id: "master_bed_read"
    dout_pin: D2
    clk_pin: D3
    gain: 128
    update_interval: 1s
  - platform: uptime
    name: "Master Bedroom Bed Uptime"
  - platform: dht
    model: DHT22
    pin: D4
    temperature:
      name: "Master Bedroom Temperature"
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Master Bedroom Humidity"
    update_interval: 10s


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Master Bedroom Bed Address"

binary_sensor:
  - platform: template
    name: "Master Bedroom Bed"
    device_class: occupancy
    lambda: if (id(master_bed_smoothed).state > 664000) return true; else return false;
