esphome:
  name: mom_and_dad_garage
  platform: ESP8266
  board: d1_mini_pro
  # platformio_options:
  #   platform: espressif8266@2.6.3
  #   platform_packages: 
  #     - platformio/toolchain-xtensa@2.40802.200502
  #     - platformio/framework-arduinoespressif8266@3.20704.0

<<: !include midnight_reboot.yaml


web_server:
  port: 80

logger:
  level: DEBUG
  
wifi:
  networks:
  - ssid: SSID
    password: WPA_KEY
  - ssid: SSID
    password: WPA_KEY
  - ssid: SSID
    password: WPA_KEY

ota:
  safe_mode: True
  password: esphome_recovery

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
    id: garage_status
    device_class: door
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

cover:
  - platform: template
    id: cover_entity
    name: "Mom and Dad Garage"
    device_class: garage
    lambda: |-
      if (id(garage_status).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: garage
    close_action:
      - switch.turn_on: garage
    stop_action:
      - switch.turn_on: garage
    
switch:
  # GPIO output for relay
  - platform: gpio
    id: relay
    pin:
      number: 5
      inverted: False

  - platform: restart
    id: reboot

  - platform: template
    id: garage
    icon: "mdi:garage"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay

mqtt:
  broker: MQTT_BROKER
  port: 1883
  # ssl_fingerprints:
  #   - 3f3077cf1c6becb8fa6dbc497ac6d9dc2a51bd42
  username: owntracks
  password: totallyowned
  log_topic: 
    topic: ${mqtt_prefix}/logs
    level: NONE
  # on_message:
  #   - topic: cmd/mom_and_dad_garage
  #     then:
  #       - switch.toggle: garage

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "Mom and Dad Garage IP Address"

sensor:
  - platform: uptime
    id: uptime_sensor
    #name: "Mom and Dad Garage Uptime"
    update_interval: 600s