esphome:
  name: mom_and_dad
  platform: ESP8266
  board: d1_mini
  on_boot:
    then:
      - binary_sensor.template.publish:
          id: automation_safety
          state: OFF
      - binary_sensor.template.publish:
          id: heading_comparison
          state: OFF

web_server:
  port: 80

wifi:
  ssid: "SSID"
  password: ""WPA_KEY""

logger:

ota:

api:

mqtt:
  broker: MQTT_BROKER
  username: gate
  password: MQTT_PASS
  log_topic:
  on_message:
#    topic: cmd/mom_and_dad_gate
    topic: cmd/test
    then:
      - script.execute: gate_toggle
      - binary_sensor.template.publish:
          id: automation_safety
          state: ON

i2c:
  sda: D2
  scl: D1
  scan: False
  
script:
  - id: gate_toggle
    then:
      if:
        condition:
          binary_sensor.is_off: automation_safety
        then:
          - switch.toggle: gate
          - delay: 30s
          - binary_sensor.template.publish:
              id: automation_safety
              state: OFF

sensor:
  - platform: qmc5883l
    address: 0x0D
#    field_strength_x:
#      name: "QMC5883L Field Strength X"
#    field_strength_y:
#      name: "QMC5883L Field Strength Y"
#    field_strength_z:
#      name: "QMC5883L Field Strength Z"
    heading:
      id: heading
      name: "Gate Sensor Heading"
    data_rate: 10Hz
    range: 200uT
    oversampling: 512x
    update_interval: 1s
  - platform: template
    id: heading_average
    name: "Gate Sensor Heading Average"
    update_interval: 1s
    unit_of_measurement: "°"
    lambda: return id(heading).state;
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 1

binary_sensor:
  - platform: template
    name: "Automation Safety"
    id: automation_safety
  - platform: template
    name: Heading Comparison Trigger
    id: heading_comparison
    lambda: |-
      if (id(heading).state > id(heading_average).state + 1.5) {
        return true;
      }
      if (id(heading).state < id(heading_average).state - 1.5) {
        return true;
      }
      else {
        return false;
      }

interval:
 - interval: 1s
   then:
     if:
       condition:
         for:
           time: 3s
           condition:
             binary_sensor.is_on: heading_comparison
       then:
         - script.execute: gate_toggle
         - binary_sensor.template.publish:
             id: automation_safety
             state: ON

switch:
  - platform: gpio
    id: relay
    pin:
      number: D1
      inverted: False
  - platform: template
    id: gate
    name: "Gate Remote"
    icon: "mdi:gate"
    turn_on_action:
    - homeassistant.service:
        service: notify.pushover
        data:
          message: "Opening!"
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
