esphome:
  name: mom_and_dad
  platform: ESP8266
  board: d1_mini
  on_boot:
    then:
      # Set initial states
      - binary_sensor.template.publish:
          id: automation_safety
          state: OFF
      - binary_sensor.template.publish:
          id: heading_comparison
          state: OFF

web_server:
  port: 80

wifi:
  ssid: "SSID"
  password: ""WPA_KEY""

logger:

ota:

api:

i2c:
  sda: D2
  scl: D1
  scan: False

script:
  - id: gate_toggle
    then:
      if:
        condition:
          binary_sensor.is_off: automation_safety
        then: 
          - binary_sensor.template.publish:
              id: automation_safety
              state: ON
          - switch.toggle: gate
          - delay: 30s
          - binary_sensor.template.publish:
              id: automation_safety
              state: OFF

mqtt:
  broker: MQTT_BROKER
  username: gate
  password: MQTT_PASS
  log_topic:
  on_message:
#    topic: cmd/mom_and_dad_gate
    topic: cmd/test
    then:
      - script.execute: gate_toggle

# Evaluate our automation every second
# only trigger gate if heading comparison has been
# true for more than 3s and safety is off
interval:
 - interval: 1s
   then:
     if:
       condition:
         and:
           - for:
               time: 3s
               condition:
                 binary_sensor.is_on: heading_comparison
           # This is intentionally duplicated
           - binary_sensor.is_off: automation_safety
       then:
         - script.execute: gate_toggle
  
sensor:
  - platform: qmc5883l
    address: 0x0D
    heading:
      id: heading
      name: "Gate Sensor Heading"
    data_rate: 10Hz
    range: 200uT
    oversampling: 512x
    update_interval: 1s
  # Template sensor to keep average of last 30 heading
  # readings so we can detect significant change
  - platform: template
    id: heading_average
    name: "Gate Sensor Heading Average"
    update_interval: 1s
    unit_of_measurement: "°"
    lambda: return id(heading).state;
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 1

binary_sensor:
  # Sensor to keep script from triggering in rapid succession
  - platform: template
    name: "Automation Safety"
    id: automation_safety
  - platform: template
    name: Heading Comparison Trigger
    id: heading_comparison
    # Set our trigger to true if heading varies from avg more than 2.5deg 
    lambda: |-
      if (id(heading).state > id(heading_average).state + 2.5) {
        return true;
      }
      if (id(heading).state < id(heading_average).state - 2.5) {
        return true;
      }
      else {
        return false;
      }
  - platform: gpio
    pin:
      number: D8
      #inverted: True
    name: Gate Status
    id: gate_status
    device_class: door
    filters:
      - delayed_on: 10ms

cover:
  - platform: template
    name: "Template Cover"
    lambda: |-
      if (id(gate_status).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - script.execute: gate_toggle
    close_action:
      - script.execute: gate_toggle
    stop_action:
      - script.execute: gate_toggle
    optimistic: true

switch:
  - platform: gpio
    id: relay
    pin:
      number: D1
      inverted: False
  - platform: template
    id: gate
    name: "Gate Remote"
    icon: "mdi:gate"
    turn_on_action:
    - homeassistant.service:
        service: notify.pushover
        data:
          message: "Opening!"
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
