substitutions:
  name: safe
  friendly_name: "Safe"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
    
<<: !include common.yaml
  
switch:
  # GPIO output for relay
  - platform: gpio
    id: safe
    name: "Safe"
    pin:
      number: D1
      inverted: False
    on_turn_on:
      - delay: 5s
      - switch.turn_off: safe