substitutions:
  name: santa_tree
  friendly_name: "Santa Tree"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml
  
switch:
  # GPIO output for relay
  - platform: gpio
    id: relay
    name: ${friendly_name}
    icon: "mdi:pine-tree"
    pin:
      number: D1
      inverted: False