esphome:
  name: server_rack
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

sensor:
  - platform: dht
    model: DHT22
    pin: D4
    temperature:
      name: "Rack Exhaust Temperature"
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Rack Exhaust Humidity"
    update_interval: 10s
  - platform: uptime
    name: "Server Rack Uptime"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Server Rack IP Address"