substitutions:
  name: sonoff_rack_fan
  friendly_name: "Rack Fan"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

fan:
  - platform: binary
    name: "${friendly_name}"
    id: rack_fan
    output: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: uptime
    update_interval: 600s
    name: "${friendly_name} Uptime"
    
switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"