esphome:
  name: sonoff_rack_fan
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "SSID"
  password: "WPA_KEY"

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Rack Fan"
    on_press:
      - fan.toggle: rack_fan

fan:
  - platform: binary
    name: "Rack Fan"
    id: rack_fan
    output: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes