substitutions:
  name: sonoff_2
  friendly_name: "Sonoff 2"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

<<: !include common.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  platform: gpio
  name: "${friendly_name} Reed Switch"
  pin:
    number: GPIO14
    inverted: yes

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

  - platform: gpio
    pin: GPIO12
    name: "${friendly_name} Switch"
