substitutions:
  name: sprinklers
  friendly_name: "Sprinkers"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  includes:
    - shift_register_switch.h
  libraries:
    - ShiftRegister74HC595@1.2

<<: !include common.yaml
  
switch:
  - platform: custom
    lambda: |-
      std::vector<switch_::Switch *> switches;
      for(int i = 0; i < 8; i++) {
          auto zone_switch = new ShiftRegisterSwitch(i);
          App.register_component(zone_switch);
          switches.push_back(zone_switch);
      }
      return switches;
    switches:
      -  name: "Sprinkler Zone 1"
         inverted: yes
         id: one
         icon: mdi:sprinkler
      -  name: "Sprinkler Zone 2"
         inverted: yes
         id: two
         icon: mdi:sprinkler
      -  name: "Sprinkler Zone 3"
         inverted: yes
         id: three
         icon: mdi:sprinkler
      -  name: "Sprinkler Zone 4"
         inverted: yes
         id: four
         icon: mdi:sprinkler
      -  name: "Sprinkler Zone 5"
         inverted: yes
         id: five
         icon: mdi:sprinkler
      -  name: "Sprinkler Zone 6"
         inverted: yes
         id: six
         icon: mdi:sprinkler
      -  name: "Sprinkler Zone 7"
         inverted: yes
         id: seven
         icon: mdi:sprinkler
      -  name: "Sprinkler Master Valve"
         inverted: yes
         id: master
         icon: mdi:valve