esphome:
  name: test
  friendly_name: test

esp8266:
  board: d1_mini

# mdns:
#   disabled: true

# Common settings to all my devices
wifi:
  ssid: "SSID"
  password: !secret wifi_password
  #output_power: 15

logger:
  level: DEBUG

api:
  #reboot_timeout: 0s
  encryption:
    key: !secret encryption_key

ota:
  safe_mode: True
  password: esphome_recovery

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address

sensor:
  - platform: uptime
    id: uptime_sensor
    name: "Uptime"
    update_interval: 30s