substitutions:
  name: traeger
  friendly_name: "Traeger"

globals:
  # Largest Distance
  - id: hopper_empty
    type: float
    initial_value: '0.28500'
  # Smallest Distance
  - id: hopper_full
    type: float
    initial_value: '0.05600'

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  
<<: !include common.yaml

spi:
  miso_pin: D0
  clk_pin: D1
  
i2c:
  - id: bus_a
    sda: D5
    scl: D6
    scan: True

sensor:
  # https://esphome.io/components/sensor/max6675.html
  - platform: max6675
    name: "${friendly_name} Temperature"
    cs_pin: D2
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    update_interval: 10s

  # https://esphome.io/components/sensor/vl53l0x.html  
  - platform: vl53l0x
    #name: "${friendly_name} Pellet Hopper"
    id: hopper_distance
    address: 0x29
    update_interval: 1s
    filters: 
      - lambda: |-
          if (x <= id(hopper_full)) {
            return id(hopper_full);
          } else if (x > (id(hopper_empty) + .05)) {
            return {};
          } else if (x >= id(hopper_empty)) {
            return id(hopper_empty);
          } else {
            return x;
          };
      - sliding_window_moving_average:
          window_size: 10
          send_every: 5

  - platform: template
    name: "${friendly_name} Hopper Level"
    update_interval: 5s
    unit_of_measurement: "%"
    lambda: |-
      return 100 - int(((id(hopper_distance).state - id(hopper_full)) / (id(hopper_empty)-id(hopper_full)))*100);
      //return int((((id(hopper_empty) - id(hopper_full)) - id(hopper_distance)) / id(hopper_empty)) * 100);

