substitutions:
  name: zoom
  friendly_name: "Zoom"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 7
    rgb_order: GRB
    name: "${friendly_name} LED"
    effects:
      - addressable_scan:
      - addressable_scan:
          name: Scan 6
          move_interval: 100ms
          scan_width: 6
      - addressable_scan:
          name: Scan 5
          move_interval: 100ms
          scan_width: 5
      - addressable_twinkle:
      - addressable_fireworks:
      - strobe:
      - addressable_flicker:

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"