version: '3.2'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        volumes:
            - '/opt/plex/db/:/config'
            - '/opt/plex/transcode/:/transcode'
            - '/plex/:/data'
            - /config
            - /transcode
        environment:
            - TZ=America/Chicago
            - PLEX_CLAIM=XXXXXXXXXXXX
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - TERM=xterm
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
            - CHANGE_CONFIG_DIR_OWNERSHIP=true
            - HOME=/config
        network_mode: host
        restart: "no"
    portainer:
        container_name: portainer
        image: portainer/portainer
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/opt/portainer:/data'
        ports:
            - '9000:9000'
        environment:
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        restart: "no"
    pihole:
      # Adding ip route proxy in /etc/rc.local
      container_name: pihole
      image: pihole/pihole:latest
      volumes:
        - '/opt/pihole/etc-pihole/:/etc/pihole/'
        - '/opt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        - '/opt/pihole/logs:/var/log'
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "8000:80/tcp"
      environment:
        TZ: 'America/Chicago'
        DNS1: '10.0.1.1'
        ServerIPv6: '2001:470:1f0f:f4:ffff:242:ac11:2'
        IPv6: 'True'
        DNSMASQ_LISTENING: all
      dns:
        - 10.0.1.1
      network_mode: 'bridge'
      restart: unless-stopped
    ozwcp:
        container_name: ozwcp
        image: openzwave/openzwave-control-panel
        volumes:
            - '/opt/homeassistant/options.xml:/etc/openzwave/options.xml'
            - '/opt/homeassistant/zwcfg_0xc564203a.xml:/etc/openzwave/zwcfg_0xc564203a.xml'
            - '/opt/homeassistant/manufacturer_specific.xml:/etc/openzwave/manufacturer_specific.xml'
        ports:
            - '8008:8008'
        devices:
            - '/dev/zwave:/dev/zwave'
        restart: 'no'
    grafana:
        container_name: grafana
        image: grafana/grafana:6.4.5
        #image: grafana/grafana
        volumes:
            - /opt/grafana:/var/lib/grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_SECURITY_COOKIE_SAMESITE=none
        restart: "no"
    esphome:
        container_name: esphome
        # This is a custom build for now. Based on https://github.com/esphome/esphome/pull/671
        image: esphome-dev
        volumes:
            - /opt/esphome/:/config:rw
            # Use local time for logging timestamps
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        restart: "no"
