version: '3.2'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        volumes:
            - '/opt/plex/db/:/config'
            - '/opt/plex/transcode/:/transcode'
            - '/plex/:/data'
            - /config
            - /transcode
        environment:
            - TZ=America/Chicago
            - PLEX_CLAIM=REDACT
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - TERM=xterm
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
            - CHANGE_CONFIG_DIR_OWNERSHIP=true
            - HOME=/config
        network_mode: host
        restart: "no"
    portainer:
        container_name: portainer
        image: portainer/portainer
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/opt/portainer:/data'
        ports:
            - '9000:9000'
        environment:
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        restart: "no"
    pihole:
        # Adding ip route proxy in /etc/rc.local
        container_name: pihole
        image: pihole/pihole:latest
        volumes:
            - '/opt/pihole/etc-pihole/:/etc/pihole/'
            - '/opt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
            - '/opt/pihole/logs:/var/log'
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8000:80/tcp"
        environment:
            - TZ='America/Chicago'
            - DNS1=10.0.1.1
            - DNS2=no
            - ServerIPv6=2001:470:1f0f:f4:ffff:242:ac11:2
            - IPv6=true
            - DNSMASQ_LISTENING=all
        dns:
            - 10.0.1.1
        #network_mode: 'bridge'
        restart: unless-stopped
    ozwcp:
        container_name: ozwcp
        image: openzwave/openzwave-control-panel
        volumes:
            - '/opt/homeassistant/options.xml:/etc/openzwave/options.xml'
            - '/opt/homeassistant/zwcfg_0xc564203a.xml:/etc/openzwave/zwcfg_0xc564203a.xml'
            - '/opt/homeassistant/manufacturer_specific.xml:/etc/openzwave/manufacturer_specific.xml'
        ports:
            - '8008:8008'
        devices:
            - '/dev/zwave:/dev/zwave'
        restart: 'no'
    grafana:
        container_name: grafana
        image: grafana/grafana:6.4.5
        #image: grafana/grafana
        volumes:
            - /opt/grafana:/var/lib/grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_SECURITY_COOKIE_SAMESITE=none
            - GF_INSTALL_PLUGINS=neocat-cal-heatmap-panel
        restart: "no"
    esphome:
        container_name: esphome
        # This is a custom build for now. Based on https://github.com/esphome/esphome/pull/671
        image: esphome-dev
        volumes:
            - /opt/esphome/:/config:rw
            # Use local time for logging timestamps
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        restart: "no"
    thermopro_mqtt:
        container_name: thermopro_mqtt
        image: aneisch/rtl_433_mqtt:latest
        environment:
            - MQTT_SERVER=10.0.1.22
            - MQTT_PORT=1883
        restart: 'no'
        devices:
            - '/dev/rtl_sdr:/dev/bus/usb/001/005'
    bitwarden:
        container_name: bitwarden
        image: bitwardenrs/server:latest
        volumes:
            - /opt/bw-data/:/data/
            - /etc/localtime:/etc/localtime:ro
        environment:
            - DISABLE_ADMIN_TOKEN=true
            - SIGNUPS_VERIFY=true
            - SIGNUPS_ALLOWED=false
            - INVITATIONS_ALLOWED=true
            - LOG_FILE=/data/bitwarden.log
            - LOG_LEVEL=error
            - EXTENDED_LOGGING=true
            - DOMAIN=REDACT
            - SMTP_HOST=REDACT
            - SMTP_FROM=REDACT
            - SMTP_FROM_NAME='Bitwarden Password Manager'
            - SMTP_SSL=true
            - SMTP_USERNAME=REDACT
            - SMTP_PASSWORD=REDACT
        ports:
            - '8777:80'
        logging:
            driver: none
        restart: always
    bitwarden_backup:
        container_name: bitwarden_backup
        image: shivpatel/bitwarden_rs_dropbox_backup:latest
        volumes:
            - /opt/bw-data/db.sqlite3:/db.sqlite3
            - /etc/localtime:/etc/localtime:ro
        environment:
            - DROPBOX_ACCESS_TOKEN=REDACT
            - BACKUP_ENCRYPTION_KEY=REDACT
        restart: always
    planefinder-stats:
        container_name: planefinder-stats
        image: aneisch/planefinder-stats
        environment:
            - INTERVAL=10
        restart: 'no'
    train-sensor:
        container_name: train-sensor
        image: aneisch/train-sensor
        devices:
            - '/dev/rtl_sdr:/dev/bus/usb/001/005'
        environment:
            - SQUELCH=80
            - HOLDOFF_TIME=800
        restart: 'on-failure'
    hass-configurator:
        container_name: configurator
        image: causticlab/hass-configurator-docker:x86_64
        ports:
          - "3218:3218/tcp"
        volumes:
          - "/opt/hass-configurator:/config"
          - "/opt/homeassistant:/hass-config"
        restart: 'no'
