version: '3.2'
services:
    homeassistant:
        container_name: hass
        image: homeassistant/home-assistant:stable
        volumes:
          - /opt/homeassistant:/config
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/aneisch/.docker_pipe:/docker_pipe
          - /tmp/radar.gif:/tmp/radar.gif
        devices:
            - /dev/zwave:/dev/zwave
        environment:
          - TZ=America/Chicago
        network_mode: host
        restart: always
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - '/etc/ssl/certs:/mosquitto/certs:ro'
            - '/opt/mqtt/config:/mosquitto/config:ro'
            - '/opt/mqtt/log:/mosquitto/log'
            - '/opt/mqtt/data:/mosquitto/data'
        ports:
            - '1883:1883'
        restart: always
    grafana:
        container_name: grafana
        image: grafana/grafana:6.4.5
        #image: grafana/grafana
        volumes:
            - /opt/grafana:/var/lib/grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_SECURITY_COOKIE_SAMESITE=none
        restart: "no"
    influxdb:
        container_name: influxdb
        image: influxdb
        volumes:
            - '/opt/influxdb:/var/lib/influxdb'
        ports:
            - '8086:8086'
        restart: always
    esphome:
        container_name: esphome
        # This is a custom build for now. Based on https://github.com/esphome/esphome/pull/671
        image: esphome-dev
        volumes:
            - /opt/esphome/:/config:rw
            # Use local time for logging timestamps
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        restart: "no"
    pwr_stat:
        # https://github.com/DanielWinks/pwrstat_docker
        container_name: pwr_stat
        image: dwinks/pwrstat_docker:latest
        hostname: pwr_stat
        volumes:
            - /opt/pwr_stat/pwrstat.yaml:/pwrstat.yaml:ro
            - /opt/pwr_stat/pwrstatd.conf:/etc/pwrstatd.conf:ro
        devices:
            # Bottom USB on back
            - '/dev/usb/hiddev0:/dev/usb/hiddev0'
        network_mode: host
        healthcheck:
            disable: true
        restart: always
    pwr_stat_650:
        # https://github.com/DanielWinks/pwrstat_docker
        container_name: pwr_stat_650
        image: dwinks/pwrstat_docker:latest
        hostname: pwr_stat_650
        volumes:
            - /opt/pwr_stat/pwrstat_650.yaml:/pwrstat.yaml:ro
            - /opt/pwr_stat/pwrstatd.conf:/etc/pwrstatd.conf:ro
        devices:
            # Top USB on back
            - '/dev/usb/hiddev1:/dev/usb/hiddev0'
        network_mode: host
        healthcheck:
            disable: true
        restart: always
    nodered:
        container_name: nodered
        image: nodered/node-red:latest
        volumes:
          - /opt/nodered:/data
          - /etc/localtime:/etc/localtime:ro
        ports:
          - "1880:1880"
        environment:
          - TZ=America/Chicago
        restart: always
    appdaemon:
        container_name: appdaemon
        image: acockburn/appdaemon:latest
        volumes:
          - /etc/localtime:/etc/localtime
          - /opt/appdaemon:/conf
        ports:
            - '8888:8888'
        restart: always
