version: '3.2'
services:
    homeassistant:
        container_name: hass
        #image: homeassistant/home-assistant:0.104.2
        image: homeassistant/home-assistant:stable
        volumes:
          - /opt/homeassistant:/config
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/aneisch/symlinks_for_rsync/hass-docker-ssh:/root/.ssh:ro
          - /tmp/radar.gif:/tmp/radar.gif
          - /sys/class/hwmon/hwmon0/temp1_input:/sys/class/thermal/thermal_zone0/temp:ro
        devices:
            - /dev/zwave:/dev/zwave
        environment:
          - TZ=America/Chicago
        network_mode: host
        restart: always
        logging:
          driver: none
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - '/etc/ssl/certs:/mosquitto/certs:ro'
            - '/opt/mqtt/config:/mosquitto/config:ro'
            - '/opt/mqtt/log:/mosquitto/log'
            - '/opt/mqtt/data:/mosquitto/data'
        ports:
            - '1883:1883'
        restart: always
    influxdb:
        container_name: influxdb
        image: influxdb
        volumes:
            - '/opt/influxdb:/var/lib/influxdb'
        ports:
            - '8086:8086'
        restart: always
    nodered:
        container_name: nodered
        image: nodered/node-red:latest
        volumes:
          - /opt/nodered:/data
          - /etc/localtime:/etc/localtime:ro
        ports:
          - "1880:1880"
        environment:
          - TZ=America/Chicago
        restart: always
    appdaemon:
        container_name: appdaemon
        image: acockburn/appdaemon:latest
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /opt/appdaemon:/conf
          # Mount directory of appdaemon apps installed by HACS
          - /opt/homeassistant/appdaemon/apps:/conf/apps/hacs
        ports:
            - '8888:8888'
        restart: always
    thermostat_mqtt:
        container_name: thermostat_mqtt
        image: aneisch/thermostat_mqtt_docker:latest
        environment:
          - MQTT_SERVER=10.0.1.22
          - MQTT_PORT=1883
          - THERMOSTAT_IP=10.0.0.29
        restart: always
    apcupsd_950:
        container_name: apcupsd_950
        image: gersilex/apcupsd
        ports:
            - '3551:3551'
        volumes:
            - /opt/apcupsd/apcupsd.conf:/etc/apcupsd/apcupsd.conf
        devices:
            - '/dev/ups_monitor_950:/dev/usb/hiddev0'
        restart: always
    apcupsd_650:
        container_name: apcupsd_650
        image: gersilex/apcupsd
        ports:
            - '3552:3551'
        volumes:
            - /opt/apcupsd/apcupsd.conf:/etc/apcupsd/apcupsd.conf
        devices:
            - '/dev/ups_monitor_650:/dev/usb/hiddev0'
        restart: always
    hass-configurator:
        container_name: configurator
        image: causticlab/hass-configurator-docker:x86_64
        restart: 'no'
        ports:
          - "3218:3218/tcp"
        volumes:
          - "/opt/hass-configurator:/config"
          - "/opt/homeassistant:/hass-config"
