script:
  fingerprint_learn:
    alias: Fingerprint Learn
    sequence:
      - service: mqtt.publish
        data:
          payload_template: "{{states('input_number.fingerprint_learning_id') | int}}"
          topic: sensor/fingerprint/mode/learning

  fingerprint_delete:
    alias: Fingerprint Delete
    sequence:
      - service: mqtt.publish
        data:
          payload_template: "{{states('input_number.fingerprint_learning_id') | int}}"
          topic: sensor/fingerprint/mode/delete

mqtt:
  sensor:
    - name: "Fingerprint"
      state_topic: "sensor/fingerprint/mode/status"
      value_template: "{{value_json.state}}"
      json_attributes_topic: "sensor/fingerprint/mode/status"
      json_attributes_template: "{{value_json | tojson}}"

sensor:
  - platform: template
    sensors:
      fingerprint_mode:
        friendly_name: "Fingerprint Sensor Mode"
        value_template: >-
          {{state_attr('sensor.fingerprint', 'mode')}}
        icon_template: >-
          {% if is_state('sensor.fingerprint_mode', 'reading') %}
            mdi:book-open-outline
          {% elif is_state('sensor.fingerprint_mode', 'learning') %}
            mdi:book-open-page-variant
          {% endif %}
      fingerprint_state:
        friendly_name: "Fingerprint State"
        value_template: >-
          {{states('sensor.fingerprint')}}
        icon_template: >-
          {% if is_state('sensor.fingerprint', 'Waiting') %}
            mdi:fingerprint
          {% elif is_state('sensor.fingerprint', 'Matched') %}
            mdi:fingerprint
          {% elif is_state('sensor.fingerprint', 'Not matched') %}
            mdi:fingerprint-off
          {% endif %}
      fingerprint_id:
        friendly_name: "Fingerprint ID"
        value_template: >-
          {{state_attr('sensor.fingerprint', 'id')}}
      fingerprint_person:
        friendly_name: "Fingerprint Person"
        value_template: >-
          {% if (states('sensor.fingerprint_id') | int > 0) and (states('sensor.fingerprint_id') | int <= 10) %}
            Andrew
          {% elif (states('sensor.fingerprint_id') | int > 10) and (states('sensor.fingerprint_id') | int <= 20) %}
            Bethany
          {% elif states('sensor.fingerprint_id') | int > 20 %}
            {{ states('sensor.fingerprint_id') }}
          {% elif is_state('sensor.fingerprint', 'Waiting') %}
            Waiting
          {% elif is_state('sensor.fingerprint', 'Not matched') %}
            Not matched
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.fingerprint', 'Waiting') %}
            mdi:human-male
          {% elif is_state('sensor.fingerprint', 'Matched') %}
            mdi:human-greeting
          {% elif is_state('sensor.fingerprint', 'Not matched') %}
            mdi:police-badge
          {% endif %}

input_number:
  fingerprint_learning_id:
    name: Fingerprint Learning ID
    min: 1
    max: 127
    step: 1
    mode: box

switch:
  - platform: mqtt
    name: Fingerprint Enabled
    unique_id: fingerprint_enabled
    icon: "mdi:lightbulb-on-outline"
    command_topic: "sensor/fingerprint/enabled"
    state_topic: "sensor/fingerprint/enabled"
    availability_topic: "sensor/fingerprint/available"
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"

#automation:
#  - alias: Disable Fingerprint After Success
#    initial_state: on
#    trigger: 
#      - platform: state
#        entity_id: sensor.fingerprint
#        to: Matched
#    action:
#      - service: switch.turn_off
#        entity_id: switch.fingerprint_enabled
#      - delay: '00:00:05'
#      - service: switch.turn_on
#        entity_id: switch.fingerprint_enabled
