automation:
  - alias: Frigate Person Offsite
    id: "frigate_person_offsite"
    mode: queued
    trigger:
      - platform: mqtt
        topic: frigate/events
        payload: true
        value_template: "{{ value_json.type == 'end' and value_json.after.label == 'person' }}"
    action:
      - delay: '00:00:05'
      - service: shell_command.frigate_clips_drive
        data:
          clip_id: "{{trigger.payload_json['after']['id']}}"

  - alias: Frigate Notification Person
    id: "frigate_notification_person"
    mode: single
    trigger:
      - platform: mqtt
        topic: frigate/events
        payload: true
        value_template: "{{ value_json.type == 'new' and value_json.after.label == 'person' }}"
    #condition: "{{ trigger.payload_json['after']['label'] == 'person' }}"
    action:
      # if home and person detection front door during the day then notify
      - if: "{{ is_state('input_boolean.security_status', 'off') and trigger.payload_json['after']['camera'] == 'front_door' and is_state('input_boolean.goodnight', 'off') }}"
        then:
          - if: "{{ is_state('binary_sensor.weasel_active', 'on') }}"
            then:
              - service: shell_command.weasel_shortcut
                data:
                  shortcut: open-front-door-cam-weasel
          - service: notify.signal_frigate
            data:
              message: >-
                A {{trigger.payload_json["after"]["label"]}} was detected.


                Clip: https://secret/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/clip.mp4


                Stream: https://secret/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr( 'camera.' ~ trigger.payload_json['after']['camera'].lower(), 'access_token')}}
              data:
                urls:
                  - http://localhost:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=1&timestamp=1&quality=100
          - delay: '00:00:10'

      # if not home or sleeping time and person detection anywhere then notify
      - if: "{{ is_state('input_boolean.security_status', 'on') or is_state('input_boolean.goodnight', 'on') }}"
        then:
          - service: notify.signal_frigate
            data:
              message: >-
                A {{trigger.payload_json["after"]["label"]}} was detected.


                Clip: https://secret/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/clip.mp4


                Stream: https://secret/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr( 'camera.' ~ trigger.payload_json['after']['camera'].lower(), 'access_token')}}
              data:
                urls:
                  - http://localhost:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=1&timestamp=1&quality=100
          - delay: '00:00:10'

  - alias: Frigate Notification Deliveries
    id: "frigate_notification_deliveries"
    mode: single
    trigger:
      - platform: mqtt
        topic: frigate/events
        payload: update
        value_template: "{{ value_json.type }}"
      - platform: mqtt
        topic: frigate/events
        payload: end
        value_template: "{{ value_json.type }}"
    condition: "{{ trigger.payload_json['after']['sub_label'] != 'Undefined' or trigger.payload_json['after']['label'] == 'PrimeAir'  }}"
    action:
      - if: "{{ 'usps' in  trigger.payload_json['after']['sub_label'] }}"
        then: 
          - service: input_datetime.set_datetime
            data:
              entity_id: "input_datetime.usps_last"
              time: "{{ ((as_timestamp(now())) | timestamp_custom('%H:%M:%S', true)) }}"
              date: "{{ (as_timestamp(now()) | timestamp_custom('%Y-%m-%d', true)) }}"
          - service: notify.signal_self
            data:
              message: "USPS detected"
              data:
                attachments:
                  - /config/images/logo.jpg
          - delay: "00:02:00"

      - if: "{{ 'PrimeAir' in  trigger.payload_json['after']['label'] }}"
        then: 
          - service: notify.signal_self
            data:
              message: "Prime Air Drone detected"
              data:
                attachments:
                  - /config/images/logo.jpg
          - delay: "00:02:00"

  - alias: Doorbell Ring
    id: "frigate_doorbell_ring"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_button_pressed
        to: "on"
    action:
      - service: camera.snapshot
        data:
          filename: /tmp/doorbell.jpg
        target:
          entity_id: camera.front_door
      - service: notify.signal_frigate
        data:
          message: >-
            Doorbell ring!

            Talk Live (you'll have to unmute audio, mic always live!): https://frigate.secret/live/webrtc/webrtc.html?src=front_door_twoway
          data:
            attachments:
              - /tmp/doorbell.jpg
      - if: "{{ is_state('binary_sensor.weasel_active', 'on') }}"
        then:
          - service: shell_command.weasel_shortcut
            data:
              shortcut: open-front-door-cam-weasel
      - service: siren.turn_on
        entity_id: siren.garage_chime_siren

  - alias: Frigate Notification Snooze
    id: "frigate_notification_snooze"
    mode: single
    trigger:
      - platform: event
        id: start
        event_type:
          - timer.started
          - timer.restarted
        event_data:
          entity_id: timer.frigate_notification_snooze
      - platform: event
        id: finish
        event_type: timer.finished
        event_data:
          entity_id: timer.frigate_notification_snooze
      - platform: state
        entity_id: automation.frigate_notification_person
        to:
          - "on"
          - "off"
        id: manual
    action:
      - if: "{{ trigger.id == 'start' }}"
        then:
          - service: homeassistant.turn_off
            entity_id: automation.frigate_notification_person
          - delay: "00:00:01"

      - if: "{{ trigger.id == 'finish' }}"
        then:
          - service: homeassistant.turn_on
            entity_id: automation.frigate_notification_person
          - service: timer.cancel
            entity_id: timer.frigate_notification_snooze
          - delay: "00:00:01"

      - if: "{{ trigger.id == 'manual' }}"
        then:
          - service: timer.cancel
            entity_id: timer.frigate_notification_snooze

  - alias: Frigate Notification Snooze Door
    id: "frigate_notification_snooze_door"
    mode: single
    trigger:
      - platform: state
        id: front_door
        entity_id: binary_sensor.front_door
        to: "on"
      - platform: event
        id: unlock
        event_type: call_service
        event_data:
          domain: lock
          service: unlock
          service_data:
            entity_id: lock.front_door
    action:
      - if: "{{ trigger.id == 'front_door' and is_state('group.trackers', 'home') and is_state('automation.frigate_notification_person', 'on') }}"
        then:
          - service: timer.start
            data:
              duration: "00:05:00"
            target:
              entity_id: timer.frigate_notification_snooze

      - if: "{{ trigger.id == 'unlock' }}"
        then:
          - service: timer.start
            data:
              duration: "00:02:00"
            target:
              entity_id: timer.frigate_notification_snooze

  - alias: Front Door Security Light
    id: "frigate_front_door_security_light"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_person_occupancy
    condition: "{{ is_state('sun.sun', 'below_horizon')}}"
    action:
      - service: select.select_option
        data:
          option: "{% if trigger.to_state.state == 'on' %}On{% elif trigger.to_state.state == 'off' %}Off{% endif %}"
        target:
          entity_id: select.front_door_security_light

  - alias: Frigate Event Creation
    id: "frigate_event_creation"
    mode: single
    trigger:
      - platform: state
        id: garage_door
        entity_id: cover.garage_door
        from: 'closed'
        to: 'open'
      - platform: state
        id: doorbell
        entity_id: binary_sensor.front_door_button_pressed
        from: 'off'
        to: 'on'
    action:
      - if: "{{ trigger.id == 'garage_door' }}"
        then:
          - service: shell_command.frigate_create_event
            data:
              camera: garage
              label: GarageDoorOpened
          - service: shell_command.frigate_create_event
            data:
              camera: driveway
              label: GarageDoorOpened
      - if: "{{ trigger.id == 'doorbell' }}"
        then:
          - service: shell_command.frigate_create_event
            data:
              camera: front_door
              label: Doorbell

  - alias: Frigate Timelapse Snapshots
    id: "frigate_timelapse_snapshots"
    mode: single
    trigger:
      - platform: time
        at: "10:00:00"
      - platform: time
        at: "14:00:00"
      - platform: time
        at: "18:00:00"
    action:
      - service: camera.snapshot
        data:
          filename: /config/timelapse/{{ '{{ entity_id.entity_id }}' }}/{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
        target:
          entity_id:
            - camera.ptz
            - camera.front_door
            - camera.driveway
            - camera.back_porch

command_line:
  - switch:
      name: Back Porch Camera White Light
      command_on: >
        curl --silent --digest -g "http://USERNAME:PASSWORD@10.0.0.32/cgi-bin/coaxialControlIO.cgi?action=control&channel=1&info[0].Type=1&info[0].IO=1"
      command_off: >
        curl --silent --digest -g "http://USERNAME:PASSWORD@10.0.0.32/cgi-bin/coaxialControlIO.cgi?action=control&channel=1&info[0].Type=1&info[0].IO=0"
      command_state: >
        curl --silent --digest -g "http://USERNAME:PASSWORD@10.0.0.32/cgi-bin/coaxialControlIO.cgi?action=getStatus&channel=0" | grep -q "status.status.WhiteLight=On"

input_datetime:
  usps_last:
    name: Last USPS Detection
    has_date: true
    has_time: true

shell_command:
  frigate_clips_drive: /config/scripts/frigate_clips_drive.sh {{ clip_id }}
  frigate_create_event: "curl -X POST --data '''{ 'duration': 30, 'include_recording': true }''' 127.0.0.1:5000/api/events/{{camera}}/{{label}}/create"

timer:
  frigate_notification_snooze:
    duration: "00:00:00"
    restore: True

media_player:
  - platform: webrtc
    name: Doorbell
    stream: front_door_twoway
    audio: pcma

# Eg:
# - service: media_player.play_media
#   target:
#     entity_id: media_player.doorbell
#   data:
#     media_content_id: media-source://media_source/media/audio.mp3
#     media_content_type: audio/mpeg

script:
  doorbell_not_interested:
    sequence:
      # - service: tts.speak
      #   target:
      #     entity_id: tts.google_en_com
      #   data:
      #     cache: false
      #     media_player_entity_id: media_player.doorbell
      #     message: "Hello. We are not interested. We hope you have a nice day!"
      - service: media_player.play_media
        target:
          entity_id: media_player.doorbell
        data:
          media_content_id: media-source://tts/microsoft?message=Hello.+We+are+not+interested.+We+hope+you+have+a+nice+day!
          media_content_type: provider
          announce: True
