# Get latest stable and beta versions
# as well as running version. Do things
# like run our current config against
# beta and stable releases to check 
# compatibility and notify of available 
# upgrade. 

sensor:
  - platform: version
    source: docker
    name: ha_docker_version_stable

  - platform: version
    beta: true
    source: docker
    name: ha_docker_version_beta

  - platform: version
    name: ha_version
    source: local

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/core/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 1800

automation:
  - alias: "Trigger Github Action"
    mode: queued
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ha_docker_version_beta
      - platform: state
        entity_id: sensor.ha_docker_version_stable
    condition:
      - condition: template
        value_template: '{{ (trigger.to_state.state != trigger.from_state.state) and (states.sensor.ha_version.state != trigger.to_state.state) }}'
    action:
      - service: shell_command.github_action_trigger
        data:
          github_token: !secret github_token
          # https://github.com/aneisch/home-assistant-config/blob/master/.github/workflows/check_ha_release-compatibility.yml
          # Options are: beta, stable
          branch: '{% if trigger.entity_id == "sensor.ha_docker_version_beta" %}beta{% elif trigger.entity_id == "sensor.ha_docker_version_stable" %}stable{% endif %}'
          release_type: >
            {% if trigger.entity_id == "sensor.ha_docker_version_beta" %}
              '{% if states('sensor.ha_docker_version_beta').split(".")[-1:][0].split("b")[0] == "0" %}major{% else %}minor{% endif %}'
            {% elif trigger.entity_id == "sensor.ha_docker_version_stable" %}
              '{% if states('sensor.ha_version')[:-2] == states('sensor.ha_docker_version_stable')[:-2] %}minor{% else %}major{% endif %}'
            {% endif %}
          version: '{{ trigger.to_state.state }}'

  # Triggered from Github action. Auto-update or notify, we only auto-apply minor releases.
  - alias: "Github Action Callback"
    initial_state: 'on'
    trigger:
      platform: webhook
      webhook_id: !secret hass_github_action_webhook
    action:
      - service: notify.pushover
        data:
          message: >
            {% if trigger.json.upgrade == True %}
              New Version Auto-Applied: {{ states('sensor.ha_version') }} --> {{ states('sensor.ha_docker_version_stable') }} 
              Changes: https://git.io/JvkT4 
              Tested: https://git.io/JvkTY
            {% elif trigger.json.upgrade == False %}
              New Version Not Auto-Applied: {{ states('sensor.ha_version') }} --> {{ states('sensor.ha_docker_version_stable') }}
              Changes: https://git.io/JvkT4
              Tested: https://git.io/JvkTY
            {% endif %}
      - service: '{% if trigger.json.upgrade == True %}shell_command.upgrade_hass{% else %}script.noop{% endif %}'

shell_command:
  github_action_trigger: "curl -v -X POST -u 'aneisch:{{ github_token }}' -H 'Accept: application/vnd.github.everest-preview+json' -H 'Content-Type: application/json' --data '{\"event_type\":\"build\", \"client_payload\":{\"branch\":\"{{ branch }}\",\"release_type\":\"{{ release_type }}\",\"version\":\"{{ version }}\"}}' https://api.github.com/repos/aneisch/home-assistant-config/dispatches"
  upgrade_hass: ssh nuc 'docker-compose -f /opt/docker-compose/unified/docker-compose.yml pull --quiet homeassistant; docker-compose -f /opt/docker-compose/unified/docker-compose.yml up -d homeassistant'

script:
  noop:
    sequence:
      delay: 00:00:00

homeassistant:
  customize:
    sensor.ha_docker_version_stable:
      icon: mdi:docker
      friendly_name: Latest Docker
    sensor.ha_docker_version_beta:
      icon: mdi:docker
      friendly_name: Beta Docker
    sensor.ha_github_version:
      icon: mdi:github
      friendly_name: Latest Github
    sensor.ha_version:
      icon: mdi:home-assistant
      friendly_name: Running Version
