# Get latest stable and beta versions
# as well as running version. Do things
# like run our current config against
# beta and stable releases to check 
# compatibility and notify of available 
# upgrade. 

sensor:
  - platform: version
    source: docker
    name: ha_docker_version_stable

  - platform: version
    beta: true
    source: docker
    name: ha_docker_version_beta

  - platform: version
    name: ha_version
    source: local

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 1800

automation:
  - alias: "Github Action Docker Beta"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.ha_docker_version_beta
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
    action:
      - service: shell_command.github_action_trigger
        data_template:
          github_token: !secret github_token
          branch: rc
          release_type: '{% if states.sensor.ha_docker_version_beta.state.split(".")[-1:][0] == ".0" %}major{% else %}minor{% endif %}'
          version: '{{ states.sensor.ha_docker_version_beta.state }}'

  - alias: "Notify Docker Update and Trigger Github Action"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.ha_docker_version_stable
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state > trigger.from_state.state }}'
    action:
      - service: shell_command.github_action_trigger
        data_template:
          github_token: !secret github_token
          # https://github.com/aneisch/home-assistant-config/blob/master/.github/workflows/check_ha_release-compatibility.yml
          # Options are: dev, rc, stable
          branch: stable
          # If release is "minor" we auto-apply the update
          release_type: '{% if states.sensor.ha_version.state[:-2] == states.sensor.ha_docker_version_stable.state[:-2] %}minor{% else %}major{% endif %}'
          version: '{{ states.sensor.ha_docker_version_stable.state }}'
      - delay:
          minutes: 6
      - service: notify.pushover
        data_template:
          message: >-
            New Version Not Auto-Applied: {{ trigger.from_state.state }} --> {{ trigger.to_state.state }} Changes: https://git.io/JvkT4 Tested: https://git.io/JvkTY

  # Triggered from Github action. We only auto-apply minor releases.
  - alias: "Upgrade HASS From Webhook"
    initial_state: 'on'
    trigger:
      platform: webhook
      webhook_id: !secret hass_upgrade_webhook
    action:
      - service: notify.pushover
        data_template:
          message: >-
            New Version Auto-Applied: {{ states.sensor.ha_docker_version_stable.state }} Changes: https://git.io/JvkT4 Tested: https://git.io/JvkTY
      - service: shell_command.upgrade_hass

shell_command:
  github_action_trigger: "curl -v -X POST -u 'aneisch:{{ github_token }}' -H 'Accept: application/vnd.github.everest-preview+json' -H 'Content-Type: application/json' --data '{\"event_type\":\"build\", \"client_payload\":{\"branch\":\"{{ branch }}\",\"release_type\":\"{{ release_type }}\",\"version\":\"{{ version }}\"}}' https://api.github.com/repos/aneisch/home-assistant-config/dispatches"

  upgrade_hass: ssh nuc 'docker-compose -f /opt/docker-compose/homeassistant/docker-compose.yml pull --quiet homeassistant; docker-compose -f /opt/docker-compose/homeassistant/docker-compose.yml up -d homeassistant'


homeassistant:
  customize:
    sensor.ha_docker_version_stable:
      icon: mdi:docker
      friendly_name: Latest Docker
    sensor.ha_docker_version_beta:
      icon: mdi:docker
      friendly_name: Beta Docker
    sensor.ha_github_version:
      icon: mdi:github-circle
      friendly_name: Latest Github
    sensor.ha_version:
      icon: mdi:home-assistant
      friendly_name: Running Version
