sensor:
  - platform: version
    beta: false
    source: docker
    name: ha_docker_version_stable

  - platform: version
    name: ha_version
    source: local
    beta: false

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name if value_json.tag_name.split('.')|length != 2 else value_json.tag_name ~ '.0' }}
    scan_interval: 1800

automation:
  - alias: "Notify Docker Update and Trigger Github Action"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.ha_docker_version_stable
    action:
      - service: shell_command.github_action_trigger
        data:
          github_token: !secret github_token
          # https://github.com/aneisch/home-assistant-config/blob/master/.github/workflows/check_ha_release-compatibility.yml
          # Options are: dev, rc, stable
          version: stable
      - delay:
          minutes: 5
      - service: notify.pushover
        data_template:
          message: >-
            New Home Assistant version available: {{ trigger.from_state.state }} --> {{ trigger.to_state.state }}. Configuration compability tested at: https://github.com/aneisch/home-assistant-config/actions

homeassistant:
  customize:
    sensor.ha_docker_version_stable:
      icon: mdi:docker
      friendly_name: Lastest Docker
    sensor.ha_github_version:
      icon: mdi:github-circle
      friendly_name: Latest Github
    sensor.ha_version:
      icon: mdi:home-assistant
      friendly_name: Running Version
