sensor:
  - platform: version
    beta: false
    source: docker
    name: ha_docker_version_stable

  - platform: version
    name: ha_version
    source: local
    beta: false

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name if value_json.tag_name.split('.')|length != 2 else value_json.tag_name ~ '.0' }}
    scan_interval: 1800

automation:
  - alias: "Notify Docker Update"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.ha_docker_version_stable
    action:
      service: notify.pushover
      data_template:
        message: >-
          New Home Assistant version available: {{ trigger.from_state.state }} --> {{ trigger.to_state.state }}

homeassistant:
  customize:
    sensor.ha_docker_version_stable:
      icon: mdi:docker
      friendly_name: Lastest Docker
    sensor.ha_github_version:
      icon: mdi:github-circle
      friendly_name: Latest Github
    sensor.ha_version:
      icon: mdi:home-assistant
      friendly_name: Running Version
