# Get latest stable and beta versions
# as well as running version. Do things
# like run our current config against
# beta and stable releases to check 
# compatibility and notify of available 
# upgrade. 

input_boolean:
  # Automation when off --> on to call upgrade
  hass_update_trigger:
    name: Upgrade HASS Now
  # Allow us to display update button on frontend when things are ready
  hass_update_available:
    name: HASS Update Available

sensor:
  - platform: version
    source: docker
    name: ha_docker_version_stable

  - platform: version
    beta: true
    source: docker
    name: ha_docker_version_beta

  - platform: version
    name: ha_version
    source: local

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/core/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 1800

automation:
  # Trigger GitHub action(s) when new version is available
  - alias: "Auto Update: Trigger Github Action"
    id: "hass_github_action"
    mode: queued
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ha_docker_version_beta
      - platform: state
        entity_id: sensor.ha_docker_version_stable
    condition: '{{ (trigger.to_state.state != trigger.from_state.state) and (states.sensor.ha_version.state != trigger.to_state.state) and (trigger.to_state.state != "unknown") }}'
    action:
      - service: shell_command.github_action_trigger
        data:
          github_token: !secret github_token
          # https://github.com/aneisch/home-assistant-config/blob/master/.github/workflows/check_ha_release-compatibility.yml
          # Options are: beta, stable
          branch: '{% if trigger.entity_id == "sensor.ha_docker_version_beta" %}beta{% elif trigger.entity_id == "sensor.ha_docker_version_stable" %}stable{% endif %}'
          release_type: >
            {% if trigger.entity_id == "sensor.ha_docker_version_beta" %}
              '{% if states('sensor.ha_docker_version_beta').split(".")[-1:][0].split("b")[0] == "0" %}major{% else %}minor{% endif %}'
            {% elif trigger.entity_id == "sensor.ha_docker_version_stable" %}
              '{% if states('sensor.ha_docker_version_stable').split(".")[-1:][0].split("b")[0] == "0" %}major{% else %}minor{% endif %}'
            {% endif %}
          version: '{{ trigger.to_state.state }}'

  # Respond to GitHub action to begin auto-upgrade flow
  - alias: "Auto Update: Github Action Callback"
    id: "auto_upgrade_boolean"
    initial_state: 'on'
    trigger:
      platform: webhook
      webhook_id: !secret hass_github_action_webhook
    action:
      service: >
        {% if trigger.json.upgrade == True %}
          script.hass_update_stage
        {% elif trigger.json.upgrade == False %}
          script.hass_update_notify
        {% endif %}

  # Actually try to upgrade if conditions are met (home and boolean on)
  - alias: "Auto Update: Install Update or Notify"
    id: auto_upgrade_upgrade"
    mode: single
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.hass_update_trigger
        from: "off"
        to: "on"
      - platform: state
        entity_id: person.andrew
        from: "not_home"
        to: "home"
    condition: '{{ states("input_boolean.hass_update_trigger") == "on" }}'
    action:
      - service: > 
          {% if states("person.andrew") == "home" %}
            script.hass_update_install
          {% else %}
            script.hass_update_notify
          {% endif %}

  - alias: "Auto Update: Set State of input_boolean.hass_update_available at Boot"
    id: "hass_update_available_boolean"
    trigger:
      - platform: homeassistant
        event: start
    condition: '{{ states("input_boolean.hass_update_available") == "on" }}'
    action:
      - delay: '00:00:30'
      - service: >
          {% if states("sensor.ha_version") == states("sensor.ha_docker_version_stable") %}
            homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.hass_update_available

shell_command:
  github_action_trigger: "curl -v -X POST -u 'aneisch:{{ github_token }}' -H 'Accept: application/vnd.github.everest-preview+json' -H 'Content-Type: application/json' --data '{\"event_type\":\"build\", \"client_payload\":{\"branch\":\"{{ branch }}\",\"release_type\":\"{{ release_type }}\",\"version\":\"{{ version }}\"}}' https://api.github.com/repos/aneisch/home-assistant-config/dispatches"
  update_hass: /config/update_hass.sh &

script:
  hass_update_stage:
    # Turn on boolean to trigger upgrade automation
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.hass_update_trigger

  hass_update_install:
    # Notify and install latest version
    sequence:
      - service: notify.pushover
        data:
          message: >
            Installing: {{ states('sensor.ha_version') }} --> {{ states('sensor.ha_docker_version_stable') }} 
            Changes: https://git.io/JvkT4 
            Tested: https://git.io/JvkTY
      - service: homeassistant.turn_off
        entity_id: input_boolean.hass_update_trigger
      - service: homeassistant.turn_off
        entity_id: input_boolean.hass_update_available
      - service: shell_command.update_hass

  hass_update_notify:
    # Notify and enable update button on frontend
    sequence:
      - service: notify.pushover
        data:
          message: >
            Not Installing: {{ states('sensor.ha_version') }} --> {{ states('sensor.ha_docker_version_stable') }}
            Changes: https://git.io/JvkT4
            Tested: https://git.io/
      - service: homeassistant.turn_on
        entity_id: input_boolean.hass_update_available

homeassistant:
  customize:
    sensor.ha_docker_version_stable:
      icon: mdi:docker
      friendly_name: Latest Docker
    sensor.ha_docker_version_beta:
      icon: mdi:docker
      friendly_name: Beta Docker
    sensor.ha_github_version:
      icon: mdi:github
      friendly_name: Latest Github
    sensor.ha_version:
      icon: mdi:home-assistant
      friendly_name: Running Version
