# switch.irrigation_24v_power                  Sprinklers 24v Power                  on       2020-09-29T12:32:44.866660+00:00
# switch.irrigation_front_beds                 Sprinklers Front Beds                 off      2020-09-29T12:32:44.915536+00:00
# switch.irrigation_front_lawn                 Sprinklers Front Lawn                 off      2020-09-29T12:32:44.915887+00:00
# switch.irrigation_left_and_main_rear_lawn    Sprinklers Left and Main Rear Lawn    off      2020-09-29T12:32:44.921695+00:00
# switch.irrigation_front_and_right_rear_lawn  Sprinklers Front and Right Rear Lawn  off      2020-09-29T12:32:44.932068+00:00
# switch.irrigation_side_lawn                  Sprinklers Side Lawn                  off      2020-09-29T12:32:44.949961+00:00
# switch.irrigation_zone_6                     Sprinklers Zone 6                     off      2020-09-29T12:32:44.969619+00:00
# switch.irrigation_zone_7                     Sprinklers Zone 7                     off      2020-09-29T12:32:44.986757+00:00
# switch.irrigation_master_valve               Sprinklers Master Valve               off      2020-09-29T12:32:45.118323+00:00

input_boolean:
  enable_irrigation_scheduling:
    name: Irrigation Auto Run
    icon: mdi:clock-time-two-outline

input_datetime:
  irrigation_front_beds_last_start: 
    name: Sprinkler Front Beds Last Start Time 
    has_date: true
    has_time: true
  irrigation_front_beds_last_stop: 
    name: Sprinkler Front Beds Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_front_lawn_last_start: 
    name: Sprinkler Front Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_front_lawn_last_stop: 
    name: Sprinkler Front Lawn Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_left_and_main_rear_lawn_last_start: 
    name: Sprinkler Left and Main Rear Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_left_and_main_rear_lawn_last_stop: 
    name: Sprinkler Left and Main Rear Lawn Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_front_and_right_rear_lawn_last_start: 
    name: Sprinkler Front and Right Rear Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_front_and_right_rear_lawn_last_stop: 
    name: Sprinkler Front and Right Rear Lawn Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_side_lawn_last_start: 
    name: Sprinkler Side Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_side_lawn_last_stop: 
    name: Sprinkler Side Lawn Last Stop Time 
    has_date: true
    has_time: true

  irrigation_master_valve_last_start: 
    name: Sprinkler Master Valve Last Start Time 
    has_date: true
    has_time: true
  irrigation_master_valve_last_stop: 
    name: Sprinkler Master Valve Last Stop Time 
    has_date: true
    has_time: true

# Used by python_script and Node Red to make a custom water cycle
input_select:
  irrigation_custom_water_1:
    name: Custom Water 1
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_2:
    name: Custom Water 2
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_3:
    name: Custom Water 3
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_4:
    name: Custom Water 4
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_5:
    name: Custom Water 5
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

sensor:
  - platform: mqtt
    state_topic: "sensor/irrigation_time_remaining"
    name: "Irrigation Time Remaining"

automation:
  - alias: Store Sprinkler Start Times
    initial_state: on
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - switch.irrigation_front_beds
        - switch.irrigation_front_lawn 
        - switch.irrigation_left_and_main_rear_lawn
        - switch.irrigation_front_and_right_rear_lawn
        - switch.irrigation_side_lawn
        - switch.irrigation_master_valve
      from: "off"
      to: "on"
      for: "00:00:30"
    action:
      - service: input_datetime.set_datetime
        data:
          entity_id: "input_datetime.{{ trigger.entity_id |regex_replace(find='switch.', replace='', ignorecase=False) }}_last_start"
          time: "{{ ((as_timestamp(now()) - 30) | timestamp_custom('%H:%M:%S', true)) }}"
          date: "{{ (as_timestamp(now()) | timestamp_custom('%Y-%m-%d', true)) }}"

  - alias: Store Sprinkler Stop Times
    initial_state: on
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - switch.irrigation_front_beds
        - switch.irrigation_front_lawn 
        - switch.irrigation_left_and_main_rear_lawn
        - switch.irrigation_front_and_right_rear_lawn
        - switch.irrigation_side_lawn
        - switch.irrigation_master_valve
      from: "on"
      to: "off"
      for: "00:00:02"
    action:
      - service: input_datetime.set_datetime
        data:
          entity_id: "input_datetime.{{ trigger.entity_id |regex_replace(find='switch.', replace='', ignorecase=False) }}_last_stop"
          time: "{{ ((as_timestamp(now()) - 2) | timestamp_custom('%H:%M:%S', true)) }}"
          date: "{{ (as_timestamp(now()) | timestamp_custom('%Y-%m-%d', true)) }}"
