template:
  - binary_sensor:
      - name: "Flume Flow Status"
        state: >-
          {{ states('sensor.flume_sensor_home_current') != "0" }}

automation:
  - alias: "Water Flow Alert"
    id: "water_flow_alert"
    trigger:
      - platform: state
        entity_id: binary_sensor.flume_flow_status
        from: "off"
        to: "on"
    # irrigation master off AND trackers away AND guest mode off
    condition: "{{ is_state('switch.irrigation_master_valve', 'off') and is_state('group.trackers', 'not_home' ) and is_state('input_boolean.guest_mode', 'off') }}"
    action:
      - service: script.notify_wrapper
        data:
          message: Unexpected water flow!
          data:
            priority: 1

  - alias: "Water Shutoff Alert"
    id: "water_shutoff_alert"
    initial_state: on
    trigger:
      - platform: state
        entity_id: switch.water_shutoff
        to: "on"
    action:
      - service: script.notify_wrapper
        data:
          message: Water supply has been shut off!
          data:
            priority: 1

  - alias: "Water Sensor Alerts"
    id: "water_sensor_alert"
    trigger:
      - platform: state
        id: non_esphome
        entity_id:
          - binary_sensor.guest_bathroom_toilet_water_detector
          - binary_sensor.back_bathroom_toilet_water_detector
          - binary_sensor.kitchen_sink_water_detector
          - binary_sensor.master_bathroom_water_detector
          - binary_sensor.water_shutoff_water_leak_detected
        to: "on"
      - platform: state
        id: esphome
        entity_id:
          - binary_sensor.laundry_room_water_detector
          - binary_sensor.water_heater_water_detector
          - binary_sensor.kitchen_water_detector
        to: "on"
    action:
      - if: "{{ trigger.id == 'non_esphome' }}"
        then:
          - service: switch.turn_on
            entity_id: switch.water_shutoff
      - service: script.notify_wrapper
        data:
          message: "Water detected by {{ trigger.to_state.name }}. {% if trigger.id == 'non_esphome' %}Shutting off water!{% endif %}"
          data:
            priority: 2
      # - service: notify.alexa_media
      #   data:
      #     message: "Water detected by {{ trigger.to_state.name }}. {% if trigger.id == 'non_esphome' %}Shutting off water!{% endif %}"
      #     data:
      #       method: all
      #       type: announce
      #     target: ["Office", "Kitchen", "Master", "Living Room"]
