script:
  magic_cube_music:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify
          # Kitchen, Office, Everywhere, etc..
          source: "{{ speakers }}"
      - service: media_player.play_media
        data:
          entity_id: media_player.spotify
          media_content_id: "{{ media }}"
          media_content_type: playlist

automation:
  - alias: "Magic Cube Aquarium"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          command: "shake"
    action:
      - service: homeassistant.toggle
        data:
          entity_id: switch.aquarium_light

  - alias: "Magic Cube Office Fan"
    mode: single
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          command: "rotate_left"
      - platform: event
        event_type: zha_event
        event_data:
          command: "rotate_right"
    action:
      - service: >
          {% if trigger.event.data['command'] == "rotate_right" %}
            homeassistant.turn_on
          {% else %}
            homeassistant.turn_off
          {% endif %}
        entity_id: switch.office_ceiling_fan
      - delay: 2

  # - alias: "Magic Cube Music Play"
  #   mode: "single"
  #   trigger:
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_1"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_2"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_3"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_4"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_5"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_6"
  #   action:
  #     - service: script.magic_cube_music
  #       data:
  #         speakers: "Kitchen"
  #         media: >
  #             {% if trigger.subtype == 'face_1' %} # Mean Girls
  #               spotify:playlist:1nPIJNvpOyH6I4BtPtlBJG
  #             {% elif trigger.subtype == 'face_2' %} # Beetlejuice
  #               spotify:album:3Nkueud4hqLWhSzOepKi7p
  #             {% elif trigger.subtype == 'face_3' %} # Hadestown
  #               spotify:album:3Nkueud4hqLWhSzOepKi7p
  #             {% endif %}
