script:
  magic_cube_music:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify
          # Kitchen, Office, Everywhere, etc..
          source: "{{ speakers }}"
      - service: media_player.play_media
        data:
          entity_id: media_player.spotify
          media_content_id: "{{ media }}"
          media_content_type: playlist

automation:
  - alias: "Magic Cube Knock or Slide"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          command: "knock"
      - platform: event
        event_type: zha_event
        event_data:
          command: "slide"
    action:
      - service: homeassistant.toggle
        data:
          entity_id: >
            {% if trigger.event.data.args["activated_face"] == 1  %}
              light.aquarium_light
            {% elif trigger.event.data.args["activated_face"] == 2 and trigger.event.data.command == "knock" %}
              switch.aquarium_filter
            {% elif trigger.event.data.args["activated_face"] == 3 %}
              switch.placeholder
            {% elif trigger.event.data.args["activated_face"] == 4 %}
              light.office_ceiling_fan
            {% elif trigger.event.data.args["activated_face"] == 5 %}
              switch.office_heater
            {% elif trigger.event.data.args["activated_face"] == 6 %}
              light.andrew_desk_lamp
            {% endif %}

  - alias: "Magic Cube Rotate"
    mode: single
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          command: "rotate_left"
      - platform: event
        event_type: zha_event
        event_data:
          command: "rotate_right"
    action:
      - service: >
          {% if trigger.event.data['command'] == "rotate_right" %}
            script.aquarium_light_increase
          {% else %}
            script.aquarium_light_decrease
          {% endif %}
      - delay: 2

  # - alias: "Magic Cube Music Play"
  #   mode: "single"
  #   trigger:
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_1"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_2"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_3"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_4"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_5"
  #     - platform: device
  #       domain: zha
  #       device_id: "ff27900c3e2b46a750d431f73d500d38"
  #       type: device_flipped
  #       subtype: "face_6"
  #   action:
  #     - service: script.magic_cube_music
  #       data:
  #         speakers: "Kitchen"
  #         media: >
  #             {% if trigger.subtype == 'face_1' %} # Mean Girls
  #               spotify:playlist:1nPIJNvpOyH6I4BtPtlBJG
  #             {% elif trigger.subtype == 'face_2' %} # Beetlejuice
  #               spotify:album:3Nkueud4hqLWhSzOepKi7p
  #             {% elif trigger.subtype == 'face_3' %} # Hadestown
  #               spotify:album:3Nkueud4hqLWhSzOepKi7p
  #             {% endif %}
