automation: 
  - alias: "Smoke Alarm Secondary"
    id: "smoke_alarm_secondary"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.kitchen_alarm_co_alarm_alarm_silenced
        - binary_sensor.kitchen_alarm_co_alarm_carbon_monoxide_detected
        - binary_sensor.kitchen_alarm_co_alarm_replacement_required_end_of_life
        - binary_sensor.kitchen_alarm_smoke_alarm_alarm_silenced
        - binary_sensor.kitchen_alarm_system_system_hardware_failure
        - binary_sensor.hallway_alarm_co_alarm_alarm_silenced
        - binary_sensor.hallway_alarm_co_alarm_carbon_monoxide_detected
        - binary_sensor.hallway_alarm_co_alarm_replacement_required_end_of_life
        - binary_sensor.hallway_alarm_smoke_alarm_alarm_silenced
        - binary_sensor.hallway_alarm_system_system_hardware_failure
      from: "off"
      to: "on"
    action:
      - service: notify.pushover
        data:
          message: >
              {{ trigger.from_state.attributes.friendly_name }}
          data:
            priority: -1
            expire: 3600
            retry: 30

  - alias: "Smoke Alarm Detection"
    id: "smoke_alarm_detection"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.kitchen_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.kitchen_alarm_smoke_alarm_smoke_detected
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_detected
      from: "off"
      to: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.smoke_alarm_triggered
      - service: notify.pushover
        data:
          message: >
              {{ trigger.from_state.attributes.friendly_name }} triggered
          data:
            priority: 2
            expire: 3600
            retry: 30

  - alias: "Smoke Alarm Clear"
    id: "smoke_alarm_clear"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.kitchen_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.kitchen_alarm_smoke_alarm_smoke_detected
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_detected
      from: "on"
      to: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.smoke_alarm_triggered
      - service: notify.pushover
        data:
          message: >
              {{ trigger.from_state.attributes.friendly_name }} cleared
          data:
            priority: 2
            expire: 3600
            retry: 30

  - alias: "Smoke Alarm Home Response"
    id: "smoke_alarm_home_response"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - input_boolean.smoke_alarm_triggered
      to: 'on'
    action:
      # If sun down, turn on some lights
      - if: "{{ states('sun.sun') == 'below_horizon' }}"
        then:
          - alias: "Turn on some Lights"
            service: homeassistant.turn_on
            data:
              brightness: 255
              transition: 5
            target:
              entity_id:
                - light.master_bedroom_lamps
                - light.kitchen_can_lights
                - light.living_room_can_lights

# script:
#   smoke_alarm_trigger_response:
#     sequence:
#       - service: homeassistant.turn_on
#         data:
#           entity_id: input_boolean.security_status
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.master_bedroom
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.common_areas

#   smoke_alarm_clear_response:
#     sequence:
#       - service: homeassistant.turn_on
#         data:
#           entity_id: input_boolean.security_status
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.master_bedroom
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.common_areas

input_boolean:
  smoke_alarm_triggered:
    name: Smoke Alarm Triggered