automation:
  - alias: "Washer Test"
    initial_state: "on"
    trigger:
      platform: webhook
      webhook_id: 82f7xefsbx7x4i5
    action:
      - service: notify.pushover
        data:
          message: Washer
      - service: input_number.increment
        entity_id: input_number.count

input_number:
  count:
    name: Slider
    min: 0
    max: 99999
