# See also: ../python_scripts/vacuum_custom_clean.py that allows custom room clean

automation:
  alias: "Roborock Go to Trashcan After Cleaning"
  trigger:
    - platform: state
      entity_id: vacuum.roborock_s4
      to: 'returning'
  condition:
    condition: state
    entity_id: input_boolean.return_to_trashcan
    state: 'on'
  action:
    - service: vacuum.pause
      entity_id: vacuum.roborock_s4
    - delay: '00:00:02'
    - service: script.vacuum_park_trashcan
    - service: homeassistant.turn_off
      entity_id: input_boolean.return_to_trashcan

sensor:
  - platform: template
    sensors:
      roborock_s4_battery:
        friendly_name: 'Roborock S4 Battery'
        value_template: "{{state_attr('vacuum.roborock_s4', 'battery_level')}}"
        unit_of_measurement: '%'
        device_class: battery

      roborock_s4_lifetime_cleaned_area:
        friendly_name: 'Lifetime Cleaned Area'
        value_template: "{{state_attr('vacuum.roborock_s4', 'total_cleaned_area')}}"
        unit_of_measurement: ㎡

      roborock_s4_lifetime_cleaning_time:
        friendly_name: 'Lifetime Cleaning Time'
        value_template: "{{(state_attr('vacuum.roborock_s4', 'total_cleaning_time') / 60)|round(1, 'floor')}}"

      # NOTE: This date is converted to be timezone aware so that it plays nice
      # with some other templating functions and filters.
      roborock_s4_last_cleaned:
        friendly_name: Relative time since last cleaning ended
        value_template: "{{relative_time(strptime(as_timestamp(state_attr('vacuum.roborock_s4', 'clean_stop'))|timestamp_custom('%Y-%m-%d %H:%M:%S%z'), '%Y-%m-%d %H:%M:%S%z'))}}"

      roborock_s4_lifetime_cleaning_count:
        friendly_name: 'Lifetime Cleaning Count'
        value_template: "{{state_attr('vacuum.roborock_s4', 'cleaning_count')}}"

     # Used for the Filter maintenance card
      roborock_s4_filter_remaining:
        friendly_name: '% Filter Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s4', 'filter_left') / 150) * 100) | round | int}}"

      # Used for the Filter maintenance card
      roborock_s4_filter_hrs_remaining:
        friendly_name: 'Filter Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s4', 'filter_left')}}"

      # Used for the Side Brush maintenance card
      roborock_s4_side_brush_remaining:
        friendly_name: '% Side Brush Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s4', 'side_brush_left') / 200) * 100) | round | int}}"
  
      # Used for the Side Brush maintenance card
      roborock_s4_side_brush_hrs_remaining:
        friendly_name: 'Side Brush Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s4', 'side_brush_left')}}"

      # Used for the Main Brush maintenance card
      roborock_s4_main_brush_remaining:
        friendly_name: '% Main Brush Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s4', 'main_brush_left') / 300) * 100) | round | int}}"

      # Used for the Main Brush maintenance card
      roborock_s4_main_brush_hrs_remaining:
        friendly_name: 'Main Brush Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s4', 'main_brush_left')}}"

      # Used for the Sensors maintenance card
      roborock_s4_sensors_remaining:
        friendly_name: '% Sensors Remaining'
        unit_of_measurement: '%'
        value_template: "{{((state_attr('vacuum.roborock_s4', 'sensor_dirty_left') / 30) * 100) | round | int}}"

      # Used for the Sensors maintenance card
      roborock_s4_sensors_hrs_remaining:
        friendly_name: 'Sensors Remaining Hours'
        unit_of_measurement: 'hrs'
        value_template: "{{state_attr('vacuum.roborock_s4', 'sensor_dirty_left')}}"

input_boolean:
  # Nodered
  roborock_daily_run:
    name: Roborock Daily Run
  return_to_trashcan:
    name: Roborock Return to Trashcan After Cleaning
    initial: 'off'

input_select:
  vacuum_room_select:
    name: Choose a room to clean
    # Define these zones in NodeRed
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom

  vacuum_custom_clean_1:
    name: Custom Clean Room 1
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom

  vacuum_custom_clean_2:
    name: Custom Clean Room 2
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      
  vacuum_custom_clean_3:
    name: Custom Clean Room 3
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom

  vacuum_custom_clean_4:
    name: Custom Clean Room 4
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      
  vacuum_custom_clean_5:
    name: Custom Clean Room 5
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      
  vacuum_custom_clean_6:
    name: Custom Clean Room 6
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      
  vacuum_custom_clean_7:
    name: Custom Clean Room 7
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom

  vacuum_custom_clean_8:
    name: Custom Clean Room 8
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      
  vacuum_custom_clean_9:
    name: Custom Clean Room 9
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      
  vacuum_custom_clean_10:
    name: Custom Clean Room 10
    initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      

script:
  vacuum_park_trashcan:
    sequence:
      - service: xiaomi_miio.vacuum_goto
        data:
          entity_id: vacuum.roborock_s4
          x_coord: 13950
          y_coord: 23250
  # {'Dining Room':24,'Kitchen':25,'Living Room':23,'Office':21,'Guest Bedroom':26,'Guest Bathroom':19,'Hallway':16,"Bethany's Office":20,'Master Bedroom':18,'Master Bathroom':19}
  # For Alexa routines
  vacuum_clean_kitchen:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 25

  vacuum_clean_living_room:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 23

  vacuum_clean_dining_room:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 24

  vacuum_clean_office:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 21

  vacuum_clean_bethany_office:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 20

  vacuum_clean_master_bedroom:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 18

  vacuum_clean_guest_bedroom:
    sequence:
      - service: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 26

switch:
  platform: template
  switches:
    # Expose vacuum switch to allow manual turn off via Alexa
    vacuum: 
      friendly_name: "Roxie"
      value_template: '{{ is_state("vacuum.roborock_s4", "on") }}'
      turn_on:
        # Dummy, do nothing
        - delay:
            seconds: 1
      turn_off:
        - service: vacuum.stop
          data:
            entity_id: vacuum.roborock_s4
        - delay: '00:00:01'
        - service: vacuum.return_to_base
          data:
            entity_id: vacuum.roborock_s4

vacuum:
  - platform: xiaomi_miio
    host: 10.0.0.10
    token: !secret roborock_token
    name: Roborock S4
