sensor:
  - platform: rest
    name: Reporting
    scan_interval: 30
    resource: https://s3.amazonaws.com/grayfilestore-kbtx/electionData/KBTX_1912_Web.json
    value_template: '{{ (value_json.Race[2].reportingNode).split("%")[0] | int }}'
    unit_of_measurement: "%"

  - platform: rest
    name: John Brick
    resource: https://s3.amazonaws.com/grayfilestore-kbtx/electionData/KBTX_1912_Web.json
    scan_interval: 30
    value_template: '{{ value_json.Race[2].candidates[0].percentage }}'
    json_attributes_path: "$.Race[2].candidates[0]"
    json_attributes:
      - firstName
      - lastName
      - voteCount
      - winner
    unit_of_measurement: "%"

  - platform: rest
    name: George Wise
    resource: https://s3.amazonaws.com/grayfilestore-kbtx/electionData/KBTX_1912_Web.json
    scan_interval: 30
    value_template: '{{ value_json.Race[2].candidates[1].percentage }}'
    json_attributes_path: "$.Race[2].candidates[1]"
    json_attributes:
      - firstName
      - lastName
      - voteCount
      - winner
    unit_of_measurement: "%"

  - platform: template
    sensors:
      john_brick_votes:
        friendly_name: "John Brick Votes"
        value_template: "{{ state_attr('sensor.john_brick', 'voteCount') | regex_replace(find=',', replace='') | int }}"
      george_wise_votes:
        friendly_name: "George Wise Votes"
        value_template: "{{ state_attr('sensor.george_wise', 'voteCount') | regex_replace(find=',', replace='') | int }}"
      judge_leader:
        friendly_name: Leader
        value_template: >
          {% if states.sensor.john_brick.state > states.sensor.george_wise.state %}
            John Brick
          {% elif states.sensor.john_brick.state < states.sensor.george_wise.state %}
            George Wise
          {% else %}
            Unknown
          {% endif %}


automation:
  - alias: "Leader Change"
    trigger:
      - platform: state
        entity_id: sensor.judge_leader
      - platform: state
        entity_id: sensor.reporting
    action:
      service: notify.pushover
      data_template:
        message: |
          Leader: {{ states.sensor.judge_leader.state }}
          Reporting: {{ states.sensor.reporting.state }}%
          Brick: {{ state_attr('sensor.john_brick', 'voteCount') }} votes
          Wise: {{ state_attr('sensor.george_wise', 'voteCount') }} votes
    
