name: Check HA Release Compatibility
# Only run when called from webhook https://github.com/marketplace/actions/repository-dispatch
on: repository_dispatch
jobs:
  check-ha-config:
    runs-on: ubuntu-latest
    steps:
      # Console output for logging
      - run: 'echo "Branch: ${{ github.event.client_payload.branch }}"'
      - run: 'echo "Release Type: ${{ github.event.client_payload.release_type }}"'
      - run: 'echo "Release Version: ${{ github.event.client_payload.version }}"'

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1   
        with:
          python-version: '3.7.x'

      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
          
      - if: github.event.client_payload.branch == 'stable'
        run: pip3 install homeassistant
        name: Install Home Assistant Stable
        
      - if: github.event.client_payload.branch == 'beta'
        run: pip3 install --pre homeassistant
        name: Install Home Assistant Beta
      
      - name: Check Config
        run: |
          mv travis_secrets.yaml secrets.yaml
          sed -i -e 's/- camera/#- camera/' -e 's/^camera/#camera/' configuration.yaml
          hass -c . --script check_config
          
  notify-or-upgrade-hass:
    runs-on: ubuntu-latest
    needs: check-ha-config
    env:
      # A stupid workaround to be able to set curl header. 
      HEADER: "Content-Type: application/json"
    steps:
      # Only apply update if minor, stable release
      - if: github.event.client_payload.branch == 'stable' && github.event.client_payload.release_type == 'minor'
        name: Upgrade HASS Minor Release
        # Call Home Assistant api and run shell_command to upgrade docker container
        # Webhook URL secret stored in github project /settings/secrets
        run: curl -sX POST -H $HEADER -d '{"upgrade":true}' ${{ secrets.HASS_WEBHOOK }} && echo "Home Assistant auto-updated successfully"

      # Call Home Assistant api and notify of major update
      - if: github.event.client_payload.branch == 'stable' && github.event.client_payload.release_type == 'major'
        name: Notify HASS Major Release
        # Webhook URL secret stored in github project /settings/secrets
        run: curl -sX POST -H $HEADER -d '{"upgrade":false}' ${{ secrets.HASS_WEBHOOK }} && echo "Home Assistant notified successfully"
