name: Check Home Assistant Release Compatibility
# Only run when called from webhook https://github.com/marketplace/actions/repository-dispatch
on: 
  repository_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - 'extras/**'

jobs:
  check-ha-config:
    name: Check Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Log Trigger Type
        run: 'echo "Trigger: ${{ github.event_name }}"'

      - name: Log Repo Dispatch Data
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Branch: ${{ github.event.client_payload.branch }}"
          echo "Release Type: ${{ github.event.client_payload.release_type }}"
          echo "Release Version: ${{ github.event.client_payload.version }}" && echo "DOCKER_TAG=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
      
      - name: Set Docker Tag
        if: github.event_name == 'push'
        run: 'echo "DOCKER_TAG=latest" >> $GITHUB_ENV'
        
      - name: Log Docker Tag
        run: 'echo "Image: ghcr.io/home-assistant/home-assistant:${{ env.DOCKER_TAG }}"'
          
      - uses: actions/checkout@v2

      - name: Check Home Assistant Config
        run: |
          docker pull -q "homeassistant/home-assistant:${{ env.DOCKER_TAG }}"
          mv github_action_secrets.yaml secrets.yaml
          sed -i -e 's/- camera/#- camera/' -e 's/^camera/#camera/' configuration.yaml

          docker run --rm --entrypoint "" \
          homeassistant/home-assistant:${{ env.DOCKER_TAG }} \
          python -m homeassistant --version

          docker run --rm -v "$(pwd):/config" --entrypoint "" \
          homeassistant/home-assistant:${{ env.DOCKER_TAG }} \
          python -m homeassistant --config "/config" --script check_config

  # Call Home Assistant Webook to instruct HASS to self-upgrade
  hass-update-install:
    name: Update Home Assistant Minor Release
    runs-on: ubuntu-latest
    # If minor release, upgrade to latest
    if: github.event.client_payload.branch == 'stable' && github.event.client_payload.release_type == 'minor'
    # Ensure config test was successful
    needs: check-ha-config
    # A stupid workaround to be able to set curl header. 
    env:
      HEADER: "Content-Type: application/json"
    steps:
        - run: curl -sX POST -H "$HEADER" -d '{"upgrade":true}' ${{ secrets.HASS_WEBHOOK }} && echo "Home Assistant update triggered"

  # Call Home Assistant Webook to instruct HASS to notify only
  hass-update-notify:
    name: Notify Home Assistant Major Release
    runs-on: ubuntu-latest
    # If major release or beta release, only send notification request
    if: (github.event.client_payload.branch == 'stable' && github.event.client_payload.release_type == 'major') || github.event.client_payload.branch == 'beta'
    # Ensure config test was successful
    needs: check-ha-config
    # A stupid workaround to be able to set curl header. 
    env:
      HEADER: "Content-Type: application/json"
    steps:
      - run: curl -sX POST -H "$HEADER" -d '{"upgrade":false}' ${{ secrets.HASS_WEBHOOK }} && echo "Home Assistant notify triggered"
