name: Check HA Release Compatibility
on: repository_dispatch
jobs:
  check-ha-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1   
        with:
          python-version: '3.7.x'
          
      - name: Install Home Assistant Stable
        if: github.event.client_payload.type == 'stable'
        run: pip3 install homeassistant
      
      - name: Install Home Assistant RC
        if: github.event.client_payload.type == 'rc'
        run: pip3 install --pre homeassistant

      - name: Install Home Assistant Dev
        if: github.event.client_payload.type == 'dev'
        run: pip3 install git+git://github.com/home-assistant/home-assistant.git@dev

      - name: Install DEPS
        run: sudo apt-get update && sudo apt-get install -y libudev-dev python-dev pkg-config

      - name: Check Config
        run: |
          mv travis_secrets.yaml secrets.yaml
          sed -i -e 's/- camera/#- camera/' -e 's/^camera/#camera/' configuration.yaml
          hass -c . --script check_config -i -f
          
  upgrade_hass:
    runs-on: ubuntu-latest
    needs: check-ha-config
    if: github.event.client_payload.type == 'stable'
    steps:
      - run: curl -X POST ${{ secrets.HASS_WEBHOOK }}
